### ISSUE TITLE
Numberbox format property

### ISSUE THREAD

**Issue by Edisson** [DevExpress/devextreme-vue#100]
### Issue Type
Bug report

### Description
I use dx-number-box in my project and initialize format property as a string (from devexpress documentation):
```
data: function () {
		return {
			numberbox: {
				value: 100.123,
				format: "$ #0.##",
			}
		}
}
```
The format is applying well but in the browser console I've got the red message::

> Invalid prop: type check failed for prop "format". Expected Object, got String.
>found in ---> <DxNumberBox> <Numberbox> at test\components\numberbox.vue

is it normal? or I do smth wrong?

**Comment by lukyanovas** [comment]
Hi! 
Yes, this is a bug in our prop types. We will fix it in future releases.
