### ISSUE TITLE
 The editCellTemplate popup inside the dxDataGrid does not work because of focus problems.

### ISSUE THREAD

**Issue by hyun-keun-cho** [DevExpress/devextreme-vue#102]
### Description

I created my own custom template using editCellTemplate.

In the custom template, dx-popup is defined. When I click dx-popup, the focus is lost on the cells of the data-grid and the pop-up closes. Is there a solution?

#### Steps to Reproduce

```
...
<dx-data-grid :dataSource="grDetailData"
                        :editing="grDetail.editing"
                        :pager="grDetail.pager"
                        :paging="grDetail.paging"
                        :columns="grDetail.columns"
                        :twoWayBindingEnabled="false"
>
    <div slot="cust" slot-scope="data">
            <my-custom-component
                               :parentForm="data"
                               :isGrid="true"
                                ref="custom"
            >
            </my-custom-component>
     </div>
</dx-data-grid>
...
```

**Comment by lukyanovas** [comment]
Hi!
I found [the similar ticket](https://www.devexpress.com/Support/Center/Question/Details/T628783).
But it seems that the problem is not the Vue integration issue.  If you need further assistance, I suggest you open a ticket in our [Support Center](https://www.devexpress.com/Support/Center)
