### ISSUE TITLE
Dx-Numberbox Invalid prop: type check failed for prop "format". Expected Object, got String.

### ISSUE THREAD

**Issue by rodrigorodriguescosta** [DevExpress/devextreme-vue#109]
### Issue Type
bug report

#### Steps to Reproduce
Using dx-numberbox format, cannot pass format property

```
 <dx-number-box          
            v-model="value"
            format="$ #0.##"
        />
```

show the error message  `Invalid prop: type check failed for prop "format". Expected Object, got String.` but the format is String and not Object. it works but show the message

**Comment by lukyanovas** [comment]
Yes, this is the same as #100
