### ISSUE TITLE
dx-tile-view slot scope

### ISSUE THREAD

**Issue by jcomet** [DevExpress/devextreme-vue#112]
### Issue Type

Question
### Description
When I implement dx-tile-view, following the example for dx-list, I get the error "Property or method "data" is not defined on the instance but referenced during render"

```javascript

                <dx-tile-view :items="actionItems">
                    <slot name="item" slot-scope="data">
                        <h5>My Item template for {{ data }}</h5>
                    </slot>
                </dx-tile-view>
```

I have tried many variations, with no success. 

```javascript
    <script type="text/javascript">
        var pageApp = new Vue({
            el: '#page',
            data: {
                actionItems: [{ name: 'Portal' }, { name: 'Reports' }]
            },

        });
    </script>
```
What is the correct way to get to the template item's data?

**Comment by lukyanovas** [comment]
Hi!
To set a slot content, rewrite your code in this manner:
```html
        <div slot="item" slot-scope="data">
            <i>This is my template for {{data}}</i>
        </div>
```
Please, check [this section](https://github.com/DevExpress/devextreme-vue#custom-templates) to know how to set DevExtreme Vue custom template.

See also:
https://codesandbox.io/s/0x2q3o9p3l
