### ISSUE TITLE
on onEditorPreparing, using onValueChanged problem

### ISSUE THREAD

**Issue by yosiah** [DevExpress/devextreme-vue#116]
Hi, 
on onEditorPreparing, using onValueChanged problem

### Issue Type
question

#### Demo
sample source code (=> https://codesandbox.io/s/8254o0o580)

Problem description

1. Change the BASIC_INFO>QTY column to 10.
2. and then The values of the WT, CBM, and Package> QTY columns of the grid are automatically calculated.
3. Click the Save button on the grid.
4. Check the output on the developer console.

(Console Description)
onValueChanged: SKU_QTY=>10
=> BASIC_INFO>QTY Changed 10.

onValueChanged: cellValue(SKU_WT)=>20
=> BASIC_INFO>WT Calculated 20 (on grid)
onValueChanged: row.data.SKU_WT=>20
=> BASIC_INFO>WT Calculated 20 (on data)

but,
The data was not changed during the storage processing.

row.data.SKU_QTY=>5
row.data.SKU_WT=>10

Edit DataSource
{"data":{"SKU_QTY":10,"SKU_WT":20,"SKU_CBM":200,"PKG_QTY":2} ...
editing data is changed.

Question
1. on ValueChanged, how to change row.data ?
grid cellValue => e.component.cellValue(e.row.rowIndex, "SKU_WT", t);
data direct change => e.row.data.SKU_WT = t;

2. on Vue 3rd party, Is 2 way bind not supported?

{screen capture}
https://www.devexpress.com/Support/Center/Attachment/GetAttachmentFile/1e100434-b962-44dc-9cb8-1fe92b2ece70

### Environment Details

- devextreme version: 18.1.4
- devextreme-vue version: 18.1.4-alpha.6
- vue version: 2.5.2

**Comment by lukyanovas** [comment]
Hi!
1) I've checked your sample and found that everything works as expected for 'batch' editing mode. The DataGrid updates the data on the save button click. You can get the updated data on the  `onRowUpdated` event.
If you have further questions in this regard, please open a [Support Center ticket](www.devexpress.com/ask) for it.

2) [This article](https://github.com/DevExpress/devextreme-vue#two-way-binding) shows how to use two-way binding with DevExtreme Vue Components.
