### ISSUE TITLE
Error in render: "TypeError: cyclic object value"  in dx-data-grid with cell template

### ISSUE THREAD

**Issue by jcomet** [DevExpress/devextreme-vue#120]
### Issue Type

bug report
### Description

using DevExtreme 18.1.4 and DevExtreme-Vue 18.1.4-alpha.6 with the following code generates "cyclic object value" error in the chrome browser console.   This issue was reported and marked as fixed in previous version, but I am experiencing the issue with current versions.

Note that I am not using a module loader.  I have a separate project to create the build as described here #84

 

    <dx-data-grid :data-source="gridData"
                  :columns="gridColumns">
        <div slot="name-column-template" slot-scope="data">
            Template For {{ data }}
        </div>
    </dx-data-grid>

    <script type="text/javascript">
        var pageApp = new Vue({
            el: '#page',
            data: { 
                gridData: [
                    { FirstName: 'Jim', LastName: 'Jones'},
                    { FirstName: 'Jon', LastName: 'Jones'},
                    { FirstName: 'Sara', LastName: 'Jones'},
                ],
                gridColumns: [
                    {
                        dataField: 'FirstName'
                    },
                    {
                        caption: 'Full Name',
                        cellTemplate: 'name-column-template'
                    },
                ]
                
            }
        });
    </script>

#### Steps to Reproduce

implement the example above to reproduce the problem
#### Current Behavior
Errors are generate in the Chrome browser console:
![image](https://user-images.githubusercontent.com/109494/42413565-141b1c20-81f1-11e8-9905-061611bb2020.png)

#### Expected Behavior
no errors and contents of data in the second column
#### Demo

I attached the output from my builder project. 
[devextreme-vue.zip](https://github.com/DevExpress/devextreme-vue/files/2172992/devextreme-vue.zip)

### Environment Details

- devextreme version: 18.1.4
- devextreme-vue version: 18.1.4-alpha.6
- vue version: 2.5.16

**Comment by jcomet** [comment]
You can also see the same problem in this sandbox (second column):
[https://codesandbox.io/s/5k4wl25p9x
](https://codesandbox.io/s/5k4wl25p9x)

**Comment by IlyaKhD** [comment]
Hi,

The thing is that the [cellTemplate](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/#cellTemplate) accepts not cell data as a parameter (`slot-scope`) but a `cellInfo` object (described [here](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/#cellTemplate)).

It causes the "converting circular structure to JSON" error - the `cellInfo` object contains a reference to a dataGrid instance, which on its turn, contains a reference to this `cellInfo`.

To fix the issue:
1) do not render the the object the template getting as param (`slot-scope`) as it is the `cellInfo`  object
2) to access the data, use `cellInfo.data` prop

e.g. this template
```html
      <div slot="testerTemplate" slot-scope="data">
        XX {{ data }} {{ data.orderId }}
      </div>
```
should look like following:
```html
      <div slot="testerTemplate" slot-scope="cell">
        XX {{ cell.data.orderId }}
      </div>
```

I've forked and updated the live example you provided: https://codesandbox.io/s/843qqk8qx2

**Comment by jcomet** [comment]
Perfect!  Thank you.
