### ISSUE TITLE
Using DevExtreme Vue Components on HTML page no webpack / transpiling 

### ISSUE THREAD

**Issue by johanjvr** [DevExpress/devextreme-vue#125]
### Issue Type
'question'

### Description

I would like to use the DevExtreme Vue components on a page were I'm just using Vue JS. 

E.g. Using standard MVC5 Razor with the Vue app initialised for just that page. I would like to use the DevExtreme Vue Editors on one of the pages where I have to enter a date. But if I use the MVC Extensions Vue complains that you can't have script in the html. 

My requirement is to just add the Javascript file for the editors like vue-datagrid so that I can use the components in my page.

**Comment by jcomet** [comment]
@johanjvr  The process is to create a little project that outputs the transpiled javascript components you want, then include them in your MVC program.   The steps are outlined in this issue #84.  I have been using this technique successfully in several MVC projects.

**Comment by johanjvr** [comment]
Thank you
