### ISSUE TITLE
[Question] Bundle size huge with only one component imported

### ISSUE THREAD

**Issue by tjq** [DevExpress/devextreme-vue#130]
### Description
The issue is related to using components from DX a la carte to reduce build size. When I build my Vue app `devextreme` comes in at a whopping 7.5MB bundle. I am only using DxDataGrid and am importing as such:

```js
import { DxDataGrid } from "devextreme-vue";
```
At no point do I import the entire library.

Is this the intended behavior, or a webpack issue? Please advise.

#### Steps to Reproduce

Here is my optimization in `webpack.config.js` for splitting chunks.

```js
optimization: {
        splitChunks: {
            chunks: 'async',
            minSize: 30000,
            minChunks: 1,
            name: true,
            cacheGroups: {
                vendors: {
                    test: '/[\\/]node_modules[\\/]/',
                    priority: -10
                },
                default: {
                    minChunks: 2,
                    priority: -20,
                    reuseExistingChunk: true
                }
            }
        }
  }      
```
### Environment Details

From `package.json`:
```js
"devextreme": "^18.1.2-pre-beta"
"devextreme-vue": "^18.1.2-alpha.3"
"webpack": "^4.15.1"
```

**Comment by lukyanovas** [comment]
Hi! 
To decrease your bundle size, use the long path to import the DevExtreme DataGrid.
```
import { DxDataGrid } from "devextreme-vue/ui/data-grid";
```
Let me know if it helps.

**Comment by tjq** [comment]
Can't believe I didn't think of that! Anyways, seems to have shuffled around the chunk sizes, but still importing the same library. I can investigate my build process a little more but I'm not importing 'devextreme-vue' anymore, only ../ui/data-grid. Will update.
