### ISSUE TITLE
Options parameter empty on dx-data-grid lookup data source.

### ISSUE THREAD

**Issue by tjq** [DevExpress/devextreme-vue#132]
### Issue Type
Question

### Description
I am having trouble extracting the row information when using a `lookup` with a `dataSource`. From the JS docs [here](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/lookup/#dataSource) it appears as though I am able to use the row data as a param. When I try to pass it as a function param, I get an empty object.

#### Steps to Reproduce
```js
{
  dataField: 'typeId',
  lookup: {
      dataSource: (options) => this.idMap['type'].filter(a => a.sysId == options.data.sysId),
      valueExpr: 'id',
      displayExpr: 'name',
   },
   width: 144,
},
```
#### Current Behavior
The `options` param returns an empty object.

#### Expected Behavior
The `options` param would return the row data, which I would use to filter the idMap where the lookup takes place.

**Comment by tjq** [comment]
@IlyaKhD

**Comment by lukyanovas** [comment]
Hi!
I suppose that the `data` exists in the `options` only in the edit mode.
Check [this DevExtreme example](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/CascadingLookups/jQuery/Light/).
I think in your case it will be something like that:
```js
lookup: {
    dataField: 'typeId',
    dataSource: (options) => {
        return {
            store: this.idMap['type'],
            filter: options.data ? ["sysId", "=", options.data.sysId] : null
        };
    },
    valueExpr: "ID",
    displayExpr: "Name"
}
```

**Comment by tjq** [comment]
Works, great -- thank you!
