### ISSUE TITLE
Popup does not refresh its content bound to an option of the root scope

### ISSUE THREAD

**Issue by NickMitrokhin** [DevExpress/devextreme-vue#133]
Take a look at [this](https://codesandbox.io/s/qv21rzy434) example. When you type the text in the input and open up the popup window by clicking the "Show value" button, the text in the popup is not refreshed.

To resolve this issue, add the "slot-scope" attribute to the popup slot.
```HTML
<div slot="content" slot-scope="data">
    <span>{{myValue}}</span> 
</div>
```

It is unclear why this attribute is required.

**Comment by lukyanovas** [comment]
We've decided to prohibit using scopeless slots in all DevExtreme Vue Components (https://github.com/DevExpress/devextreme-vue/pull/138).

Scopeless template evaluates and renders inside component on component rendering and cannot be deferred. It may cause conflict with such DevExtreme features as `deferRendering` and etc.

Use scoped slot:
```html
    <dx-popup :visible.sync="isVisible" contentTemplate="content">
      <div slot="content" slot-scope="_">
        <span>{{myValue}}</span> 
      </div>
    </dx-popup>
```
or default slot (18.1.5-alpha.8):
```html
    <dx-popup :visible.sync="isVisible">
        <span>{{myValue}}</span> 
    </dx-popup>
```
