### ISSUE TITLE
Missing DxCol and DxRow from DxResponsivBox

### ISSUE THREAD

**Issue by Rebolon** [DevExpress/devextreme-vue#134]
### Issue Type
issue

### Description
DxResponsiveBox need more documentation. It's easy to import the DxResponsiveBox, but there is no info about how using columns and rows and it seems that no DxCol neither DxRow exists.
And in fact there is no way to import DxCol and DxRow components

**Comment by IlyaKhD** [comment]
Hi,

Have you tried importing these components (`DxCol` and `DxRow`) using the full module path?

```js
import {
  DxResponsiveBox,
  DxCol,
  DxRow
} from "devextreme-vue/ui/data-grid";
```
See [responsive-box.d.ts](https://unpkg.com/devextreme-vue@18.1.4-alpha.7/ui/responsive-box.d.ts).

**Comment by IlyaKhD** [comment]
See this [example](https://codesandbox.io/s/2jpjjzy0y).

For further questions on DevExtreme libraries and widgets' APIs, use the [DevExpress Support Center](https://www.devexpress.com/Support/Center).
