### ISSUE TITLE
Form - The "button" item does not apply button settings

### ISSUE THREAD

**Issue by NickMitrokhin** [DevExpress/devextreme-vue#140]
Hi,

Take a look at [this](https://codesandbox.io/s/pn8900l5m) example. The button is rendered, but button options are not applied.

**Comment by IlyaKhD** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Vue: Forms improvement](https://trello.com/c/OUnG5Qbw/555-vue-forms-improvement)
