### ISSUE TITLE
onClick: function () on Add/Edit button

### ISSUE THREAD

**Issue by Delari** [DevExpress/devextreme-vue#142]
Hello, Please tell me how to implement on your data-grid event clicking on the add or edit buttons

my Vue list component (list.vue)

I want that when I click the add or edit button I open the corresponding component (Add.vue | edit.vue), but I do not know how to do it

javascript exemple

     onEditingStart: function (e) {
        e.cancel = true;
        window.location.href = "/Roles/Edit/" + e.data.Id;
     },

but can't do this on Vue

    <template>
        <div>
            <span v-if="false">Loading...</span>
            <dx-data-grid
            :editing="{ allowUpdating: true, allowDeleting: true, useIcons: true }"
            ....
            :columns="columns">
            </dx-data-grid>
        </div>    
    </template>
    <script>
    import { DxDataGrid,
        ....
      } from 'devextreme-vue/ui/data-grid'
    export default ({
        components: {
            DxDataGrid,
                ....
        },
        data() {
            return {
                columns: [{
                    dataField: "Name",
                    caption: "Name",
                    sortOrder: "asc"
            },
                ....
            ],
            onEditingStart: function (e) {
                e.cancel = true;
                alert('Alert show');    <-- that work
                },
                .......
            };
        },       
     });
     </script>

**Comment by Delari** [comment]
try this, add

    import CreateVue from './Create.vue'
    Vue.use(VueRouter)
    export const router = new VueRouter({
    routes: [
        {
        name: 'Create',
        path: './Create',
        component: CreateVue,
        props: { name: 'Создать'}
        }]
    });

and in data -> return

    onToolbarPreparing: function (e) {
        var toolbarItems = e.toolbarOptions.items;
        toolbarItems.push({
        widget: 'dxButton',
        options: {
                icon: 'add', onClick: function () {
                        router.push({ name: 'Create' })
                }
        location: 'after'
        });
    },
but not work

**Comment by AlexanderKovalenko** [comment]
Hi,

If you need to refresh the grid, call its [refresh](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Methods/#refresh) method. You can get the component instance in the **e.component** argument of the onToolbarPreparing event. See also: [Getting a Widget Instance](https://github.com/DevExpress/devextreme-vue#getting-a-widget-instance)
