### ISSUE TITLE
The Class prop overrides DevExtreme classes

### ISSUE THREAD

**Issue by IlyaKhD** [DevExpress/devextreme-vue#149]
### Issue Type
bug report

### Description

The issue is related to all components

#### Steps to Reproduce
Change any component class after it was initialized

#### Current Behavior
dx-* classes removed
#### Expected Behavior
dx-* classes remain

### Environment Details

- devextreme-vue version: 18.1.5-alpha.8

**Comment by lukyanovas** [comment]
Vue does not get access to a `class` property. We will investigate how to fix this issue.
As a workaround, you can wrap the DevExtreme widget in a `div` and set your class it.

**Comment by IlyaKhD** [comment]
Vue has some restrictions for the case. From the https://github.com/vuejs/vue/issues/3975:
>This is expected behaviour in 2.0, since these changes can't be reflected in the virtualDOM and get therefore overriden during updates.

**Comment by LexDX** [comment]
We are unable to fix this issue because of Vue 2.0 limitations. We will consider this modification once Vue 3.0 is released.
