### ISSUE TITLE
DataGrid and EditorTemplate

### ISSUE THREAD

**Issue by genusP** [DevExpress/devextreme-vue#157]
### Issue Type
bug report

### Description
If I define editorTemplate for column with custom Vue component.  When open editor in popup mode throw error.

#### Steps to Reproduce
```html
<dx-data-grid :dataSource="departments"
                  :editing="{ mode:'popup', allowUpdating:true, allowAdding:true}">
        <dxi-column caption="Подразделение" 
                   dataField="DepartmentId" 
                   editCellTemplate="departmentsEditor" 
                   :lookup="{dataSource:departmentsList, displayExpr:'Name', valueExpr:'Id'}"
                   :validationRules="[{type:'required'}]"></dxi-column>
<div slot="departmentsEditor" slot-scope="cellInfo">
            <ric-departments-drop-down :departmentId="cellInfo.value" 
                                       :showClearButton="false"
                                       @update:departmentId="cellInfo.setValue($event)">
            </ric-departments-drop-down>
</div>
</dx-data-grid>
```

#### Current Behavior
Throws error:
Uncaught TypeError: Cannot set property 'dxValidator' of undefined
    at Object.exports.attachInstanceToElement (public_component.js:34)
    at inheritor.ctor (dom_component.js:42)
    at inheritor.eval [as ctor] (class.js:17)
    at new inheritor (class.js:96)
    at inheritor.createValidator (ui.grid_core.validating.js:189)
    at inheritor._formItemPrepared (ui.grid_core.validating.js:610)
    at inheritor.eval [as _formItemPrepared] (class.js:17)
    at inheritor._updateCell (ui.grid_core.editing.js:1719)
    at inheritor.eval [as _updateCell] (class.js:17)
    at inheritor._updateCell (ui.grid_core.search.js:304)

### Environment Details

- devextreme version: 18.1.6
- devextreme-vue version: 18.1.6-alpha.9
- vue version: 2.1.5

**Comment by lukyanovas** [comment]
Hi!
Could you please modify [this example](https://codesandbox.io/s/github/lukyanovas/devextreme-vue-example) to show the issue?

**Comment by lukyanovas** [comment]
I've checked the example and found this issue is not related to the Vue integration. I have created a corresponding ticket [T680925](https://www.devexpress.com/Support/Center/Question/Details/T680925) in our Support Center.
