### ISSUE TITLE
dxForm value not update from code

### ISSUE THREAD

**Issue by genusP** [DevExpress/devextreme-vue#164]
### Issue Type
bug report

### Description
 Form values not updated when changed from code and duplicate nested configuration objects
#### Steps to Reproduce
[Example](https://codesandbox.io/s/5zj7q5ojkp)
 Click two or more on hyperlink with text Increment field 2. Look on Nested configuration count value and output formData object.
#### Current Behavior
Displayed value not update
#### Expected Behavior
Update displayed value

### Environment Details

- devextreme version: 18.1.6
- devextreme-vue version: 18.1.6-alpaha.9
- vue version: 2.5.2

**Comment by lukyanovas** [comment]
Fixed #159

**Comment by genusP** [comment]
Why every render add new instance nested configuration?

**Comment by IlyaKhD** [comment]
@genusP, I've filed a new issue for that: #178. Thank you.
