### ISSUE TITLE
[Question] How to utilize templates?

### ISSUE THREAD

**Issue by needo2** [DevExpress/devextreme-vue#172]
For grid, `cellTemplate="foo"` works with `<div scope="foo">`
But I can't achive the same functionality with forms
Can get `<div data-options="{dxTemplate: {name: 'foo'}}">` to work but it breaks when I add `slote-scope`

**Comment by lukyanovas** [comment]
Hi!
To set the template in DevExtreme Vue use [scoped slots](https://github.com/DevExpress/devextreme-vue#custom-templates).
Could you please send me a sample to show the lack of slots functionality?

**Comment by needo2** [comment]
Two examples: https://codesandbox.io/s/jjxrrwo8my
One for dx-data-grid toolbar template and other for dx-form item template

**Comment by lukyanovas** [comment]
Use the following syntax:
```html
 <div slot="toolbarTemplate" slot-scope="templateData">
    Toolbar Template
 </div>
  ...
 <div slot="melTemplate" slot-scope="templateData">
    Mel Template
 </div>
```
instead of
```
 <div scope="toolbarTemplate">
    Toolbar Template
 </div>
  ...
 <div scope="melTemplate">
    Mel Template
 </div>
```

I've updated your [sample](https://codesandbox.io/s/kro8wp5kr) to show you approach.
Read more about markup customization [here](https://github.com/DevExpress/devextreme-vue#custom-templates).

**Comment by needo2** [comment]
Okay, my bad, I was so sure it didn't work with slot-scope
