### ISSUE TITLE
How get column information on calculateCellValue handler

### ISSUE THREAD

**Issue by genusP** [DevExpress/devextreme-vue#187]
### Issue Type
question

### Description
Documentation wrote
```
The this keyword refers to the column's configuration.
```
In devextreme-vue this refers to component.

#### Current Behavior
This refers to this component

#### Expected Behavior
This refers to column configuration

### Environment Details

    "devextreme": "18.1.7-pre-18291",
    "devextreme-vue": "18.1.7-alpha.10"
    "vue": "2.5.17",

**Comment by lukyanovas** [comment]
You can add your handler of `calculateCellValue`  to component data without context binding.

```html
<dx-column data-field="City"
     data-type="string"
     :calculateCellValue="calculateCellValue" 
/>
```
```js
    data() {
        return {
            //...
            calculateCellValue(cellInfo) {
              console.log(this);
              return '123';
            }
        };
    },
```
See the [sample ](https://codesandbox.io/s/jlkl9zo5oy)
