### ISSUE TITLE
dxValidator not work outside dx components

### ISSUE THREAD

**Issue by genusP** [DevExpress/devextreme-vue#195]
### Description

For implement additional validation logic my custom editor, I place dx-validator inside DIV and set adapter.

#### Current Behavior
Validator not work. Property instace == undefined

#### Expected Behavior
Validate data 
### Environment Details

- devextreme version: 18.1.7
- devextreme-vue version: 18.1.7-alpaha.10
- vue version: 2.5.7

**Comment by lukyanovas** [comment]
Hi,
DevExtreme Vue Validator works only as an extension to DevExtreme Vue editors. We will consider providing support for a standalone Validator. Now you can use [DevExtreme Validator](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxValidator/) directly as a JS component to overcome the issue.

**Comment by genusP** [comment]
My work around
```js
mounted() {
        setTimeout(() => {
            var validator: any = this.$refs["filesValidator"];
            validator.attachTo(validator.$el);
        },100);
    }
```

**Comment by sreekarsudireddy** [comment]
@genusP Can you please provide a code sample.

Thank you!

**Comment by genusP** [comment]
https://github.com/IlyaKhD/devextreme-vue/blob/3f0083437b3cb3577b0b4ffacb914e515beef58e/example/components/validation-example.vue#L31
