### ISSUE TITLE
DxDropDownBox throw error if value prop not set

### ISSUE THREAD

**Issue by muratyuceer** [DevExpress/devextreme-vue#199]
### Issue Type
'bug report'

### Description
DxDropDownBox started throw error if value prop not set or set null
Error in mounted hook: "TypeError: Cannot read property 'length' of undefined"

### Environment Details
- devextreme version: 18.2.3
- devextreme-vue version: 18.2.3
- vue version: 2.5.17

**Comment by lukyanovas** [comment]
I've published [new version](https://www.npmjs.com/package/devextreme-vue/v/18.2.4-beta.1) of devextreme-vue, that contains the fix of this issue.
