### ISSUE TITLE
DxList  Error in mounted hook: "TypeError: Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by muratyuceer** [DevExpress/devextreme-vue#200]
Issue Type
'bug report'

Description
DxListBox started throw error if you delete all items from list
Error in mounted hook: "TypeError: Cannot read property 'length' of undefined"

Environment Details
devextreme version: 18.2.3
devextreme-vue version: 18.2.3
vue version: 2.5.17

**Comment by muratyuceer** [comment]
It's an emergency

**Comment by lukyanovas** [comment]
I've published [new version](https://www.npmjs.com/package/devextreme-vue/v/18.2.4-beta.1) of devextreme-vue, that contains the fix of this issue.
