### ISSUE TITLE
TypeError: Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by MNITD** [DevExpress/devextreme-vue#213]
I am writing  frontend part on laravel-nova project, where Tools of dashboard are vue components

### Issue Type
bug report

### Description
This issue related to named slotes and slote scopes. When trying to use any widget while customizing templates get error in console and nothing is rendered. 

#### Current Behavior
Nothing is rendered and error in console. Top red line points to the part of code where item element is DOM Node of type comment 
![image](https://user-images.githubusercontent.com/17023655/49819834-04eb3f00-fd7f-11e8-9354-787983aee39e.png) I believe it could be because **item-template** value has been parsed as String and in context of html it could be only comment

#### Expected Behavior
Implementing custom template 

#### Demo

**components/Tool.vue**
```
<template>
        <dx-list :items="items" item-template="my-template">
            <div slot="my-template" slot-scope="data">
                <i>This is my template for {{data}}</i>
            </div>
        </dx-list>
</template>

<script>
    import { DxList } from 'devextreme-vue'

    export default {
        components:{
            DxList,
        },
        data: function () {
            return {
               items: [1,2,3,4]
            }
        }
}
</script>
```
**tools.js**
```
Nova.booting((Vue, router) => {
	router.addRoutes([
		{
			name: 'Chat',
			path: '/Chat',
			component: require('./components/Tool'),
		},
	])
});
```

### Environment Details
- ubuntu: 16.04
- node: 10.12
- devextreme: ^18.2.3
- devextreme-vue: ^18.2.3
- vue: ^2.5.0
- laravel-mix: ^1.0

**Comment by IlyaKhD** [comment]
Hi,

We were unable to reproduce the issue, check [this codesandbox](https://codesandbox.io/s/5kp73rn0pn?module=%2Fsrc%2Fcomponents%2Fexample.vue).

Could you modify the example above to demonstrate the problem?
