### ISSUE TITLE
DxTagBox:  (dataSource) "TypeError: Cannot read property 'length' of undefined" 

### ISSUE THREAD

**Issue by daru23** [DevExpress/devextreme-vue#217]
### Issue Type
Question - Bug

### Description
Trying to use DxTagBox Component and it seems like it doesn't read the dataSource. If you can point what am I doing wrong please or if it is a bug in the component. Thanks.

#### Current Behavior
It always give this error back 
![screenshot 2018-12-14 at 13 33 54](https://user-images.githubusercontent.com/1735875/50003728-0007d480-ffa5-11e8-8d29-03506fdaa6e5.png)

#### Demo
```vue
<template>
    <div>
        {{customSource.length}}
        <dx-tag-box :dataSource="customSource" displayExpr="name" valueExpr="id" :searchEnabled="true"></dx-tag-box>
    </div>
</template>

<script>
    import {DxTagBox} from 'devextreme-vue';

    export default {
        components: {DxTagBox,},
        data: function() {
            return {
                customSource: [
                    { id: 1, name: 'English'},
                    { id: 2, name: 'Spanish'},
                ],
            }
        },
    }
</script>

<style scoped></style>
```

### Environment Details
- devextreme version: 18.2.3
- devextreme-vue version: 18.2.3
- vue version:2.5.17

**Comment by lukyanovas** [comment]
Hi!
I've published [new version](https://www.npmjs.com/package/devextreme-vue/v/18.2.4-beta.1) of devextreme-vue, that contains the fix of this issue.
Take a look on [the example](https://codesandbox.io/s/mo88j6owpp) with new version.

https://github.com/DevExpress/devextreme-vue/issues/200

**Comment by daru23** [comment]
It works now. Thanks
