### ISSUE TITLE
Getting exeptions when use vue + compilator

### ISSUE THREAD

**Issue by evgencode** [DevExpress/devextreme-vue#221]
### Description
When I use 
```import Vue from 'vue'```
 everything is good, 
BUT, when I use 
```import Vue from 'vue/dist/vue';```
 (vue Runtime + Compilator) - I see a bug when I try to change the dataSource after mounting.

#### Steps to Reproduce
Have a look there: https://codesandbox.io/s/9y7wq8q96p
Open console, you will see exceptions in 2.5 seconds

#### Current Behavior
![image](https://user-images.githubusercontent.com/2129431/50335971-06a2c880-051e-11e9-8a4a-39ab1802e473.png)

#### Expected Behavior
Rerender without exeptions

### Environment Details

- devextreme version: 18.2.3
- devextreme-vue version: 18.2.3
- vue version: 2.5.21

**Comment by evgencode** [comment]
Any solutions for this?

**Comment by lukyanovas** [comment]
Please, take a look at [this issue](https://github.com/DevExpress/devextreme-vue/issues/90). I think the reason is the same.

**Comment by IlyaKhD** [comment]
I suppose the issue was related to fact that the Vue library was included twice (see https://github.com/DevExpress/devextreme-vue/issues/90#issuecomment-395037510).
