### ISSUE TITLE
Scroll in Drop Down Box

### ISSUE THREAD

**Issue by alfin87aa** [DevExpress/devextreme-vue#224]
### Issue Type

bug report

### Description

Drop Down Box can't scrolling item.

![image](https://user-images.githubusercontent.com/9900492/50529845-7a4e6200-0b2a-11e9-9691-494a9bf9e99e.png)

#### Demo

https://js.devexpress.com/Demos/WidgetsGallery/Demo/DropDownBox/SingleSelection/Vue/Light/

### Environment Details

- devextreme version: 18.2.3
- devextreme-vue version: 18.2.3
- vue version: 2.5.21

**Comment by DokaRus** [comment]
Hi,

This behavior is related to the demo, not widget.
The DataGrid `height` option should be `100%` in this demo. We'll fix it ASAP.

**Comment by alfin87aa** [comment]
> Hi,
> 
> This behavior is related to the demo, not widget.
> The DataGrid `height` option should be `100%` in this demo. We'll fix it ASAP.

Hi,

great it's work thanks for your help, and how i use the drop down in data grid.

**Comment by alfin87aa** [comment]
> Hi,
> 
> This behavior is related to the demo, not widget.
> The DataGrid `height` option should be `100%` in this demo. We'll fix it ASAP.

Dear DokaRus,

i get this same issue again even though i set height in the DataGrid to 100% but still can't scrolling after update the devextreme and vue,i really need your help, thank you.

Environment Details
devextreme version: 18.2.6
devextreme-vue version: 18.2.6
vue version: 2.6.7
