### ISSUE TITLE
DxLookup ( in a grid) vs DxLookup (standalone)

### ISSUE THREAD

**Issue by jcomet** [DevExpress/devextreme-vue#225]
### Issue Type

question
### Description

There seems to be component naming conflicts within DevExtreme Vue.   For example, how does one use a dx-lookup component, as well as a dx-lookup column in the same component considering that you can't include dx-lookup from both sources.

#### Steps to Reproduce

Add a dx-lookup component to an app, then add a dx-data-grid with a column that contains a dx-lookup 
#### Current Behavior
only one of the lookups work, depending on where you import it from
#### Expected Behavior
both components work
#### Demo

I modified the cascading lookups example to illustrate:

https://codesandbox.io/s/kmp37jqknv?module=%2FApp.vue

### Environment Details

- devextreme version: 18.2.4
- devextreme-vue version: 18.2.4
- vue version: 2.5.16

**Comment by AlexanderKovalenko** [comment]
Hi,

Thank you for contacting us. I see that you created the corresponding issue in our [Support Center](https://www.devexpress.com/Support/Center/Question/Details/T704178/dxlookup-in-a-grid-vs-dxlookup-standalone). It has been placed in our processing queue and will be answered shortly.
