### ISSUE TITLE
Use a DxDropDown in editor when adding a row.

### ISSUE THREAD

**Issue by steelcg** [DevExpress/devextreme-vue#227]
### Issue Type

bug report
question

### Description

The issue is related to DxDataGrid

#### Steps to Reproduce
I have one column which value is from another array with some properties. So i want use a DxDropDown in editor when adding a row. 
1. add editor-preparing.
``` html
              <dx-data-grid
                :data-source="config.dataSource"
                :columns="config.columns"
                :show-borders="true"
                :paging="config.paging"
                :pager="config.pager"
                :headerFilter="config.headerFilter"
                :row-alternation-enabled="true"
                :show-row-lines="true"
                :loadPanel="{ enabled: true }"
                :editing="config.editing"
                :keyExpr="config.keyExpr"
                @row-inserted="config.event.rowInserted"
                @row-updated="config.event.rowUpdated"
                @row-removed="config.event.rowRemoved"
                @editor-preparing="config.event.editorPreparing"
              />
```
2. add a property in data
``` javascript
data() {
  return {
    event: {
      ...
      editorPreparing: e => {
        if (e.parentType == "dataRow" && e.dataField=="Users" ) {
          e.editorName = "dxDropDownBox";
          e.editorOptions.dropDownOptions = { height: 500 };
          e.editorOptions.contentTemplate = function(args, container) {
            console.log(args, container);
          };
        }
      }
    }
}
```
3. console.log(args, container); was not executed.

#### Current Behavior
contentTemplate call back was not executed
#### Expected Behavior
contentTemplate call back was executed

BTW
I wonder if there is another way to implement my require.
### Environment Details

- devextreme version:^18.2.4
- devextreme-vue version:^18.2.4
- vue version:^2.5.17

**Comment by IlyaKhD** [comment]
Hi!
What about the [lookup option](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/lookup/)? See [demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/CascadingLookups/jQuery/Light/).

**Comment by IlyaKhD** [comment]
About using dxDropDownBox: check this [example](https://codesandbox.io/s/3xpo8j0n4p)

Note that the dxDropDownBox has to be imported explicitly:

```import "devextreme-vue/drop-down-box";```

For further questions on DevExtreme libraries and widgets' APIs, use the [DevExpress Support Center](https://www.devexpress.com/Support/Center).
