### ISSUE TITLE
The "Found 2 elements with non-unique id" error occurs 

### ISSUE THREAD

**Issue by geods3** [DevExpress/devextreme-vue#229]
### Issue Type 
bug report

### Description
in DataGrid on editing mode row when filterrow enabled and set oneditorpreparing like this for password field

onEditorPreparing(e) {
   if(e.parentType == "dataRow" && e.dataField == "password"){ 
     e.editorOptions.mode = "password"
   }
}

and returns this error in console:

[DOM] Found 2 elements with non-unique id #dx-col-1: (More info: https://goo.gl/9p2vKq) <input autocomplete=​"off" id=​"dx-col-1" class=​"dx-texteditor-input" type=​"text" spellcheck=​"false" tabindex=​"0" role=​"textbox" style=​"text-align:​ left;​">​ <input autocomplete=​"off" id=​"dx-col-1" class=​"dx-texteditor-input" type=​"text" spellcheck=​"false" tabindex=​"0" role=​"textbox" style=​"text-align:​ left;​">​
[DOM] Found 2 elements with non-unique id #dx-col-2: (More info: https://goo.gl/9p2vKq) <input autocomplete=​"off" id=​"dx-col-2" class=​"dx-texteditor-input" type=​"text" spellcheck=​"false" tabindex=​"0" role=​"textbox" style=​"text-align:​ left;​">​ <input autocomplete=​"off" id=​"dx-col-2" class=​"dx-texteditor-input" type=​"text" spellcheck=​"false" tabindex=​"0" role=​"textbox" style=​"text-align:​ left;​">​
[DOM] Found 2 elements with non-unique id #dx-col-3: (More info: https://goo.gl/9p2vKq) <input autocomplete=​"off" id=​"dx-col-3" class=​"dx-texteditor-input" type=​"text" spellcheck=​"false" tabindex=​"0" role=​"textbox" style=​"text-align:​ left;​">​ <input autocomplete=​"off" id=​"dx-col-3" class=​"dx-texteditor-input" type=​"text" spellcheck=​"false" tabindex=​"0" role=​"textbox" style=​"text-align:​ left;​">​

i found that filterrow and row has the same id in input element of each column..... this happens only in edit mode row as i see. if i disable filterrow then all seems ok...

### Environment Details

- devextreme version: 18.2.5
- devextreme-vue version: 18.2.5
- nuxt version: 2.3.1

**Comment by artem-kurchenko** [comment]
Hi,

Thank you for the report. We fixed this issue in v.18.2.6. Please update both "devextreme" and "devextreme-vue" and check if the problem persists.
