### ISSUE TITLE
validationCallback is called continuously and cannot be stopped in validationRules of column property when dataType is date

### ISSUE THREAD

**Issue by steelcg** [DevExpress/devextreme-vue#230]
### Issue Type
bug report

### Description

The issue is related to dxdatagrid validation
validationCallback is called continuously and cannot be stopped in validationRules of column property when dataType is date

#### Steps to Reproduce
blow is a column setting.
```javascript
{
    dataField: "bookDate",
    dataType: "date",
    caption: "Book Date",
    format: "yyyy-MM-dd",
    editorOptions: {
        showClearButton: true,
        calendarOptions: { showTodayButton: true },
        dateSerializationFormat: "yyyy-MM-dd",
        acceptCustomValue: false
    },
    validationRules: [
        {
            type: "required",
            message: "Book Date is required."
        },
        {
            type: "custom",
            validationCallback: async e => {
                console.info("validationCallback invoked");
                let tempData = await webapi.getBookDate(e.value);
                e.rule.isValid = tempData.length == 0;
                e.rule.message = e.rule.isValid ? null : "The Book Date is exist.";
                e.validator.validate();
                return false;
            }
        }
    ]
}
```
when add a row or update, once i set value to this column, the validationCallback  is called continuously and cannot be stopped.

i have tested in a popular column withsame situation. no problem.
### Environment Details

- devextreme version:^18.2.5
- devextreme-vue version:^18.2.5
- vue version:^2.5.17

**Comment by artem-kurchenko** [comment]
Hi,

Thank you for the detailed description.  Validation callback doesn't support async calls out of the box, so we cannot guarantee that such logic will work properly in all cases. 

Async validation support is in our Roadmap for 2019 (see this [blog](https://community.devexpress.com/blogs/javascript/archive/2019/01/22/devextreme-javascript-2019-roadmap.aspx)) 

I'd like to add that this forum is devoted to the problems related to Vue specifics. 
For quick and detailed assistance,  feel free to contact us in [Support Center](https://www.devexpress.com/support/center/question/create)
