### ISSUE TITLE
How to define cellTemplate

### ISSUE THREAD

**Issue by Belala** [DevExpress/devextreme-vue#232]
```
<template>
  <dx-data-grid
    :columns="cols"
    :show-borders="showBorders"
    :data-source="dataSource"
    :remote-operations="remote"
    :pager="pager"
  >
    <dx-paging :page-size="10"/>
    <dx-filter-row :visible="showFilterRow" :apply-filter="currentFilter"/>
    <slot></slot>
  </dx-data-grid>
</template>
```
i create a components, but when i use it , cell template can not work;
how to fix it?

**Comment by artem-kurchenko** [comment]
Hi,

We have the [Column Template](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/ColumnTemplate/Vue/Light/) demo demonstrating how to define cell templates. In addition, check the [Custom Templates](https://github.com/DevExpress/devextreme-vue#custom-templates) help section describing common concepts.
