### ISSUE TITLE
TreeView LoadData on Demand Uncaught (in promise) TypeError: Cannot read property 'internalFields' of null

### ISSUE THREAD

**Issue by daru23** [DevExpress/devextreme-vue#234]
### Issue Type
Question, Bug Report

### Description
I am creating a TreeView Loading Data on Demand using createChildren method, but every time a node is clicked to be expanded I get the follow error in the console (see bellow). Therefor the loading icon next to the item is always shown and the arrow disappear. I saw in the examples for JQuery and the rootValue is set as a string "0" but somehow for VueJS that prop is restrict to Object. I was wondering if it has something to do with this and if not, why is this error showing.

Thanks ahead for your help.

```
Uncaught (in promise) TypeError: Cannot read property 'internalFields' of null
    at inheritor._updateParentsState (ui.tree_view.base.js:948)
    at inheritor._renderSublevel (ui.tree_view.base.js:552)
    at ui.tree_view.base.js:687
    at _Deferred.<anonymous> (deferred.js:46)
    at Callback.push../node_modules/devextreme/core/utils/callbacks.js.Callback._fireCore (callbacks.js:24)
    at Callback.push../node_modules/devextreme/core/utils/callbacks.js.Callback.fireWith (callbacks.js:76)
    at Callback.push../node_modules/devextreme/core/utils/callbacks.js.Callback.fire (callbacks.js:84)
    at _Deferred.(.../anonymous function) [as resolveWith] (...vendors.js?Ver=310120190910:36941:23)
    at deferred.js:112
```
#### Demo
```
dx-tree-view id="sites-tree-view" data-structure="plain"
                              :searchEnabled="true"
                              displayExpr="displayName"
                              keyExpr="id" parentId="id"
                              :virtualModeEnabled="true"
                              :dataSource="store"
                              :createChildren="createChildren"
                              :rootValue="{}"
                ></dx-tree-view>

createChildren(parent) {
            let parentId = parent ? parent.key : "";
            return new Promise((resolve, reject) => {
                if (!parentId) {
                    this.getSites().then((sites) => {
                        resolve(sites);
                    }).catch((e) => reject(e))
                } else {
                    this.getSubSites(parentId).then((subSites) => {
                        resolve(subSites);
                    }).catch((e) => {reject(e)})
                }
            })
}
```

### Environment Details
- devextreme version: 18.2.5
- devextreme-vue version: 18.2.5
- vue version: 2.5.17

**Comment by artem-kurchenko** [comment]
Hi,

Thank you for the call stack. It looks like the issue occurs because rootValue is set as an empty object.
Try defining this option as a number or an empty string. For instance, check the following example - https://codesandbox.io/s/q42xqn8rq

As for the prop warning, we'll correct in the next minor releases. You can ignore it for now as it doesn't affect component operation.

**Comment by daru23** [comment]
Yes, that was the problem. Thanks a lot.

**Comment by amirhosein993** [comment]
Hello. After setting the rootValue to an empty string still I have this error. what else should I do to resolve it?
Thanks.
