### ISSUE TITLE
Stackoverflow when use mixins

### ISSUE THREAD

**Issue by genusP** [DevExpress/devextreme-vue#246]
I write few mixins for extends component behavior. First mixin register globality, others register to dx components.

# Bug Report
When register global mini and for component then throw error Stackoverflow.

**Package versions:**

    devexteme version: 18.2.6
    devextreme-vue version: 18.2.6

**Steps to reproduce:**

https://codesandbox.io/s/6y937zpq8w
Open console to see error

**Current behavior:**
Throw error.

**Expected behavior:**
Work without errors.

**Comment by artem-kurchenko** [comment]
Hi,

I checked this case, and cannot say that it's a good idea to assign mixins at runtime to our wrappers as they define all data internally. 

As far as I can see, the recommended approach is to assign mixins when a component is created (e.g. for when creating custom components that can contain our wrappers). A similar scenario was discussed at [How to dynamically inject a mixin into component](https://stackoverflow.com/questions/42758408/how-to-dynamically-inject-a-mixin-into-component)

Anyway, it's possible to extend our components to add mixins - https://codesandbox.io/s/y0vkx9po9j
I'd like to clarify that it's not a part of the documented API and we cannot guruantee that it will work properly.
Would you please clarify what logic you're trying to extract into a separate  object in case of using our components? We'll check if there alternative options.

**Comment by genusP** [comment]
After change registration by your recommendation, no stackoverflow error.
If I add my mixin to configuration components the they throw error.
```
TypeError: Cannot read property 'init' of undefined
    at VueComponent.beforeMount (configuration-component.js:22)
``` 

In my app exists service implementing list of named data sources. My mixin add property for seting datasource name and implements logic for setup dataSource, diplayExpr and valueExpr property values

**Comment by genusP** [comment]
As workaround I use old variant registration mixin for configuration components

**Comment by artem-kurchenko** [comment]
Configuration components are designed to configure nested options for our widgets (for better syntax). It's not clear why they need to contain mixins that expose information about an application service. 
I cannot guarantee that any workaround will work in the future. The best option would be to register Vue mixins at the standard Vue component level and use our widgets inside such components. 
In addition, it's possible to use [defaultOptions](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxAccordion/Methods/#defaultOptionsrule
) to specify common settings for widgets at the application level.
