### ISSUE TITLE
Form - The "TypeError: Cannot read property 'add' of undefined" error occurs in vue 2.6.7

### ISSUE THREAD

**Issue by genusP** [DevExpress/devextreme-vue#247]
# Bug Report

When define nested options for simple item the for not rendered

**Package versions:**

    devexteme version: 18.2.6
    devextreme-vue version: 18.2.6
    vue : 2.6.7

**Steps to reproduce:**

https://codesandbox.io/s/xvw4vwnxl4

**Current behavior:**

Throw error - TypeError: Cannot read property 'add' of undefined

**Expected behavior:**

No errors
**Screenshots:**

**Comment by artem-kurchenko** [comment]
Hi,

Thank you for the report. We're working on this issue in the [T718266](https://www.devexpress.com/Support/Center/Question/Details/T718266/form-the-cannot-read-property-add-of-undefined-error-occurs-if-nested-components-are) thread. Please bear with us.
