### ISSUE TITLE
[Nesting Dx-Item itemType="group"] doesnt work

### ISSUE THREAD

**Issue by faststare08** [DevExpress/devextreme-vue#249]
please kindly fix about nesting component.
I have a simple form, simple nesting dx-item but it doesnt work in vue. and doesnt render at all and throw an error.

    <dx-form 
    :slot="form" 
    :ref="form" 
    :colCount="1" 
    >
        <dx-item itemType="tabbed">
            <dx-tab title="Company">
                <dx-item 
                    dataField="taxType" 
                    editorType="dxSelectBox" 
                    :editorOptions="{ 'items' : taxTypeItems, 'displayExpr' : 'desc', 'valueExpr' : 'id' }"
                >
                </dx-item>
                <dx-item dataField="registerName" editorType="dxTextBox"></dx-item>
                <dx-item itemType="group" caption="Individual Taxpayer">
                    <dx-item dataField="registerName" editorType="dxTextBox"></dx-item>
                </dx-item>
            </dx-tab>
        </dx-item>
    </dx-form>

error:
    vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 
    'itemType' of undefined"

    found in

    ---> <DxForm>
           <Form>
             <DxPopup>
               <CompanyForm> at src/components/form/Company.vue
                 <CompanyDataGrid> at src/components/datagrid/Company.vue
                   <Company> at src/views/Company.vue
                     <App> at src/App.vue
                       <Root>
    warn @ vue.runtime.esm.js?2b0e:619
    logError @ vue.runtime.esm.js?2b0e:1883
    globalHandleError @ vue.runtime.esm.js?2b0e:1878
    handleError @ vue.runtime.esm.js?2b0e:1839
    invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1861
    callHook @ vue.runtime.esm.js?2b0e:4194
    insert @ vue.runtime.esm.js?2b0e:3132
    invokeInsertHook @ vue.runtime.esm.js?2b0e:6311
    patch @ vue.runtime.esm.js?2b0e:6530
    Vue._update @ vue.runtime.esm.js?2b0e:3920
    updateComponent @ vue.runtime.esm.js?2b0e:4041
    get @ vue.runtime.esm.js?2b0e:4444
    Watcher @ vue.runtime.esm.js?2b0e:4433
    mountComponent @ vue.runtime.esm.js?2b0e:4048
    Vue.$mount @ vue.runtime.esm.js?2b0e:8377
    render @ component.js?d710:146
    render @ ui.widget.js?cc15:218
    _renderContentImpl @ ui.overlay.js?b370:729
    (anonymous) @ class.js?e6aa:17
    _renderContentImpl @ popup.js?205e:263
    (anonymous) @ class.js?e6aa:17
    (anonymous) @ ui.widget.js?cc15:301
    deferExecute @ common.js?2809:63
    deferRender @ common.js?2809:84
    _renderContent @ ui.widget.js?cc15:300
    _renderContent @ ui.overlay.js?b370:698
    (anonymous) @ class.js?e6aa:17
    _renderVisibility @ ui.overlay.js?b370:549
    (anonymous) @ ui.overlay.js?b370:445
    _show @ ui.overlay.js?b370:463
    _renderVisibilityAnimate @ ui.overlay.js?b370:408
    _optionChanged @ ui.overlay.js?b370:1093
    (anonymous) @ class.js?e6aa:17
    _optionChanged @ popup.js?205e:581
    (anonymous) @ class.js?e6aa:17
    _notifyOptionChanged @ component.js?b9dd:324
    setOption @ component.js?b9dd:521
    (anonymous) @ component.js?b9dd:541
    (anonymous) @ component.js?d710:64
    Configuration.updateValue @ configuration.js?8e7b:140
    (anonymous) @ configuration.js?8e7b:177
    run @ vue.runtime.esm.js?2b0e:4533
    flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4275
    (anonymous) @ vue.runtime.esm.js?2b0e:1979
    flushCallbacks @ vue.runtime.esm.js?2b0e:1905
    Promise.then (async)
    timerFunc @ vue.runtime.esm.js?2b0e:1932
    nextTick @ vue.runtime.esm.js?2b0e:1989
    queueWatcher @ vue.runtime.esm.js?2b0e:4367
    update @ vue.runtime.esm.js?2b0e:4509
    notify @ vue.runtime.esm.js?2b0e:730
    reactiveSetter @ vue.runtime.esm.js?2b0e:1055
    onClick @ Company.vue?f387:114
    execute @ action.js?51d3:129
    _executeAction @ action.js?51d3:93
    execute @ action.js?51d3:65
    (anonymous) @ component.js?b9dd:366
    result @ component.js?b9dd:398
    _executeClickAction @ button.js?5cf5:205
    (anonymous) @ button.js?5cf5:201
    callHandler @ events_engine.js?8de2:121
    wrappedHandler @ events_engine.js?8de2:144
    handleCallback @ events_engine.js?8de2:220
    callHandlers @ events_engine.js?8de2:224
    (anonymous) @ events_engine.js?8de2:409
    (anonymous) @ events_engine.js?8de2:290
    applyForEach @ events_engine.js?8de2:71
    (anonymous) @ events_engine.js?8de2:86
    object.(anonymous function) @ dependency_injector.js?7960:24
    fireEvent @ utils.js?2433:181
    clickHandler @ click.js?5c27:90
    callHandler @ events_engine.js?8de2:121
    wrappedHandler @ events_engine.js?8de2:144
    handleCallback @ events_engine.js?8de2:220
    callHandlers @ events_engine.js?8de2:224
    (anonymous) @ events_engine.js?8de2:235
    vue.runtime.esm.js?2b0e:1887 TypeError: Cannot read property 'itemType' of undefined
        at inheritor._prepareGroupItem (ui.form.js?30f8:320)
        at inheritor._prepareItems (ui.form.js?30f8:305)
        at inheritor._renderLayout (ui.form.js?30f8:353)
        at inheritor._initMarkup (ui.form.js?30f8:244)
        at inheritor.eval [as _initMarkup] (class.js?e6aa:17)
        at inheritor._renderComponent (dom_component.js?4c43:68)
        at inheritor.endUpdate (dom_component.js?4c43:281)
        at inheritor.eval [as endUpdate] (class.js?e6aa:17)
        at inheritor.endUpdate (ui.widget.js?cc15:641)
        at inheritor.eval [as endUpdate] (class.js?e6aa:17)

**Comment by genusP** [comment]
What you using version vue. 
If version great or equals is 2.6 then this issue duplicate #247
