### ISSUE TITLE
DxMap gives Vue warning: '"key" is a reserved attribute and cannot be used as component prop.'

### ISSUE THREAD

**Issue by WietseMank** [DevExpress/devextreme-vue#250]
devexteme version: 18.2.6
devextreme-vue version: 18.2.6

How to reproduce: Just add a dxmap control to a page.
For example see: https://codesandbox.io/s/x9q9n2129z

In the console a '[Vue warn]: "key" is a reserved attribute and cannot be used as component prop.' is shown.

**Comment by artem-kurchenko** [comment]
@IlyaKhD Could you please check if we can remove this warning without renaming the [dxMap.key](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxMap/Configuration/key/) option?

**Comment by IlyaKhD** [comment]
Added this to our backlog.

The warning itself is harmless, but if the `key` attribute is set, it will be cleaned off before widget is initialized.

@WietseMank, note that you have to import the `DxKey` component to set `DxMap`'s `key` option:
```html
<dx-key
    google="api-key-goes-here"
    bing="api-key-goes-here"
    googleStatic="api-key-goes-here"
/>
```
