### ISSUE TITLE
Datagrid multiselect fail if used with summary and selectionChanged event

### ISSUE THREAD

**Issue by botura** [DevExpress/devextreme-vue#254]
# Bug Report

**Package versions:**

    devexteme version: 18.2
    devextreme-vue version: 18.2

**Steps to reproduce:**
https://codesandbox.io/embed/mqommw092y?fontsize=14

Pressing shift and left click to select a range of rows fail in certain conditions.
In the example provided I'm using the selectionChanged event to sum the selected amounts.
But range selection works properly only in some conditions:
1) If I remove `<dx-summary ... `section from template
2) Or if I remove `<div>Total = {{ total }}</div>` from template

Following is the code I've adapted from DevExtreme Demo: [https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/MultipleRecordSelectionModes/Vue/Light/](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/MultipleRecordSelectionModes/Vue/Light/)
```
<template>
  <div>
    <dx-data-grid
      :data-source="sales"
      :show-borders="true"
      key-expr="orderId"
      @selectionChanged="selectionChanged"
    >
      <dx-column :width="90" data-field="orderId" caption="Order ID" />
      <dx-column data-field="city" />
      <dx-column :width="180" data-field="country" />
      <dx-column data-field="region" />
      <dx-column data-field="date" data-type="date" />
      <dx-column :width="90" data-field="amount" format="currency" />

      <dx-paging :page-size="10" />
      <dx-selection
        :select-all-mode="allMode"
        :show-check-boxes-mode="checkBoxesMode"
        mode="multiple"
      />
      <dx-filter-row :visible="true" />

      <dx-group-panel :visible="true" />

      <dx-summary>
        <dx-group-item
          column="idString"
          summaryType="count"
          displayFormat="{0} lançamentos"
        />

        <dx-group-item
          column="amount"
          summaryType="sum"
          displayFormat="total {0}"
          :valueFormat="{
            style: 'currency',
            currency: 'BRL',
            minimumFractionDigits: 2
          }"
        />
      </dx-summary>
    </dx-data-grid>

    <div>Total = {{ total }}</div>

    <div class="options">
      <div class="caption">Options</div>
      <div class="option">
        <span>Select All Mode</span>
        <dx-select-box
          id="select-all-mode"
          :data-source="['allPages', 'page']"
          :disabled="checkBoxesMode === 'none'"
          v-model="allMode"
        />
      </div>
      <div class="option checkboxes-mode">
        <span>Show Checkboxes Mode</span>
        <dx-select-box
          id="show-checkboxes-mode"
          :data-source="['none', 'onClick', 'onLongTap', 'always']"
          v-model="checkBoxesMode"
        />
      </div>
    </div>
  </div>
</template>
<script>
import { sales } from "./data.js";
import { DxSelectBox } from "devextreme-vue";
import {
  DxDataGrid,
  DxColumn,
  DxPaging,
  DxSelection,
  DxFilterRow,
  DxSummary,
  DxGroupItem,
  DxGroupPanel,
  DxScrolling
} from "devextreme-vue/data-grid";

export default {
  components: {
    DxSelectBox,
    DxDataGrid,
    DxColumn,
    DxPaging,
    DxSelection,
    DxFilterRow,
    DxSummary,
    DxGroupItem,
    DxGroupPanel,
    DxScrolling
  },
  data() {
    return {
      allMode: "allPages",
      checkBoxesMode: "onClick",
      sales,
      total: 0
    };
  },

  methods: {
    selectionChanged(e) {
      this.total = 0;
      for (let i = 0; i < e.selectedRowsData.length; i++) {
        this.total += e.selectedRowsData[i].amount;
      }
    }
  }
};
</script>
<style scoped>
.options {
  margin-top: 20px;
  padding: 20px;
  background-color: rgba(191, 191, 191, 0.15);
  position: relative;
}

.caption {
  font-size: 18px;
  font-weight: 500;
}

.option {
  margin-top: 10px;
}

.checkboxes-mode {
  position: absolute;
  right: 20px;
  bottom: 20px;
}

.option > .dx-selectbox {
  width: 150px;
  display: inline-block;
  vertical-align: middle;
}

.option > span {
  margin-right: 10px;
}
</style>

```

**Current behavior:**

**Expected behavior:**

**Screenshots:**

**Comment by botura** [comment]
I've found another issue that happens when using selectionChanged and some other data grid functions.

How to reproduce:
1) Open this [CodeSandBox](https://codesandbox.io/embed/1r81j20xp3?fontsize=14). It was adapted from [this DevExtreme example](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/RecordGrouping/Vue/Light/)

2) Click on Expand All Groups to disable the checkbox. Data grid will retract.
3) Click on any state to expand it.
4) Select any row from that state and all data grid will be retracted again.
5) Remove the`value-format` line from from the second `dx-group-item` and it will work as expected.
`
:value-format="{
type: 'fixedPoint',
precision: 2
}"
`
6) Now undo the last step and remove `@selectionChanged="selectionChanged"`. It will also work as expected.

**Comment by artem-kurchenko** [comment]
Hi @botura ,

Vue double-checks all bindings after any binding is changed. So, the following code always assigns a new object to a summary item.
` :valueFormat="{
style: 'currency',
currency: 'BRL',
minimumFractionDigits: 2
}"`
As a result UI changes are lost because the widget is redrawn. You need to define valueFormat as a separate variable. 
 
For instance, check the following example - https://codesandbox.io/s/x3v2loz6wo
 
Note that this approach should be used for any complex option to avoid re-rendering in such cases

**Comment by botura** [comment]
Hi @artem-kurchenko ,

Thanks for your response. 

Your example solved the selecting issue, but `:valueFormat="valueFormat"` is not formating the sum. 
Is there any workaround for this?

**Comment by botura** [comment]
Using a string in valueFormat solves it:

`valueFormat="#,###.00"`

Now I got everything working!
