### ISSUE TITLE
 [Vue warn]: Invalid prop: custom validator check failed for prop "widget".

### ISSUE THREAD

**Issue by smallkite** [DevExpress/devextreme-vue#257]
# Bug Report

**Package versions:**

    devexteme version: 18.2.6
    devextreme-vue version: 18.2.6

**Steps to reproduce:**
Use  dx-toolbar-item in dx-popup
Set  widget="dxDropDownMenu"
Example:
dx-toolbar-item
                widget="dxDropDownMenu"
                :options="actionOptions"
                location="before"
dx-toolbar-item

**Current behavior:**

Error message in console : Invalid prop: custom validator check failed for prop "widget".
**Expected behavior:**

Not error message in console

**Screenshots:**

**Comment by dxvladislavvolkov** [comment]
@smallkite hi,
dxDropDownMenu is not a valid value for the widget option.
You can see all the accepted values [here](https://js.devexpress.com/Documentation/19_1/ApiReference/UI_Widgets/dxToolbar/Default_Item_Template/#widget).
We're going to introduce the dxDropDownButton widget in the upcoming v19.1 It should be possible to use it as a toolbar item
