### ISSUE TITLE
cell-template error after 19.1.3 in dx-column

### ISSUE THREAD

**Issue by vns-santin** [DevExpress/devextreme-vue#276]
# Support Question

Hi guys, 

I recently tried to update to 19.1.3. After that, I am getting the error on my cell-templates for the dx-grid components.

<template>
  <dx-data-grid
    height="100%"
    width="100%"
    :data-source="data"
    :show-borders="false"
    :show-column-lines="false"
    :show-row-lines="true"
    :hover-state-enabled="true"
  >
    <dx-scrolling mode="virtual" />
    <dx-search-panel
      :visible="true"
      :width="240"
      placeholder="Search..."
    />
    <dx-column-chooser :enabled="true" />
    <dx-selection mode="multiple" />
    <dx-group-panel :visible="true" />
    <dx-grouping :auto-expand-all="false" />

    <dx-column
      :min-width="150"
      cell-template="template"
      data-field="project"
      caption="Project"
    ></dx-column>

    <div slot="template" slot-scope="{ data }">
      <nuxt-link
        class="btn-link"
        :to="'/' + data.id"
        >{{ data.project.name}}</nuxt-link
      >
    </div>
  </dx-data-grid>
</template>

Error: 
Cannot read property 'name' of undefined

Does something change for the binding?

Thanks

**Comment by smallkite** [comment]
I am getting the error  on my templates for the dx-form: 
`<dx-form
                :form-data="data"
                :items="items"
        >
                <div slot="link" slot-scope="{ editorOptions }">
                        <i>This is my template for {{editorOptions.value}}</i>
                </div>
        </dx-form>`

Error in render: "TypeError: Cannot read property 'value' of undefined"

**Comment by IlyaKhD** [comment]
Hi
Template syntax has changed in v19.1.3 (see this [note](https://www.devexpress.com/Support/Center/VersionHistory?TechnologyName=DevExtreme&PlatformName=Vue&ProductName=AllProducts&VersionHistoryItemsType=&StartBuildName=19.1.3&EndBuildName=19.1.3#BC5079))

In short, you have to update the template in this way:

```diff
-<div slot="link" slot-scope="{ editorOptions }">
+<div slot="link" slot-scope="{ data: { editorOptions } }">
```
