### ISSUE TITLE
Render a component inside  dx-tooltip for dx-chart

### ISSUE THREAD

**Issue by vns-santin** [DevExpress/devextreme-vue#296]
Hi, I am trying to find a way to render a component inside a chart tooltip. 
Is it possible to do return it from the HTML properties in the customize-tooltip function? For example:

`<dx-tooltip :enabled="true" :customize-tooltip="customTooltip" />`
` methods: {
    customTooltip: arg => {
      return {
        html: '<div><span>Testing</span><br/> <dx-number-box :value="2"/></div>'
      }
    },
  },`

**Comment by roman-simionov** [comment]
Hi @vns-santin,
 
At the moment, the chart's built-in tooltip doesn't allow creating another component inside itself.
 
You can use our dxTooltip component to accomplish this task. Here is [a sample](https://codesandbox.io/s/tooltip-html-support-devextreme-charts-k50su).
