### ISSUE TITLE
TypeError: Cannot read property 'exportDataGrid' of undefined

### ISSUE THREAD

**Issue by wolfzhang** [DevExpress/devextreme-vue#313]
Advanced Document Customization,
[Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'exportDataGrid' of undefined"
https://codesandbox.io/s/m2wj9

**Comment by LexDX** [comment]
It looks like we fixed this issue in the latest version of our components. Please check the following CodeSandBox example:
https://codesandbox.io/s/vm147
I do not have any errors or warnings in it.
