### ISSUE TITLE
the row dbclick event

### ISSUE THREAD

**Issue by ZouHuaYi** [DevExpress/devextreme-vue#339]
# Feature request

 **Package versions you currently use:**

    devexteme version: 
    devextreme-vue version: 18.2.6

 **Description:**

Don't have row dbclick event only click event

 **Preferred Solution:**

 **Alternatives:**

**Additional Context:**

**Comment by LexDX** [comment]
We added this functionality in version 19.1. Please refer to [onRowDblClick](https://js.devexpress.com/Documentation/19_1/ApiReference/UI_Widgets/dxDataGrid/Configuration/#onRowDblClick%5D(https://js.devexpress.com/Documentation/19_1/ApiReference/UI_Widgets/dxDataGrid/Configuration/#onRowDblClick)) for more information.
