### ISSUE TITLE
Vue SelectBox with dataSource in IE11 not working

### ISSUE THREAD

**Issue by nanatsusaia** [DevExpress/devextreme-vue#341]
# Bug Report

Hi DevExtreme Team,
when use a dataSource property in SelectBox under vue, the Internet Explorer 11 throw an error. You can also open the demo example with the IE11, the vue example not works:
https://js.devexpress.com/Demos/WidgetsGallery/Demo/SelectBox/GroupedItems/Vue/Light/

**Package versions:**

    devexteme version: 19,2,4
    devextreme-vue version: 19.2.4

Best regards

**Comment by LexDX** [comment]
Thank you for the report. I reproduced this issue and we are researching why it occurs:

https://www.devexpress.com/Support/Center/Question/Details/T848942/devextreme-vue-demos-does-not-work-in-ie-11

We will update this ticket once we have any results.
