### ISSUE TITLE
Typescript Definition Error - Cannot find namespace 'VueType'.

### ISSUE THREAD

**Issue by coolhome** [DevExpress/devextreme-vue#342]
### Issue Type
Typescript definitions throw error on build. I created a new vue cli4 project w/ typescript, babel, eslint & prettier. 

This is the following error, however it does build fine and works just fine.

Below is my first example of using Composition + TSX. This error will occur on a standard cli new project as well.
```
ERROR in C:/Users/Preston/Desktop/AuthorizationServer/dashboard/node_modules/devextreme-vue/button.d.ts(19,61):
19:61 Cannot find namespace 'VueType'.
    17 |     readonly instance?: Button;
    18 | }
  > 19 | declare const DxButton: import("vue/types/vue").ExtendedVue<VueType.default, unknown, unknown, {
       |                                                             ^
    20 |     instance: Button;
    21 | }, {
    22 |     accessKey: string;
```

I followed the guide - https://js.devexpress.com/Documentation/Guide/Vue_Components/Add_DevExtreme_to_a_Vue_Application/

## main.ts
```
import Vue from "vue";
import VueCompositionApi from "@vue/composition-api";
import router from "./router";
import store from "./store";
import App from "./App";

Vue.config.productionTip = false;
Vue.use(VueCompositionApi);

import "devextreme/dist/css/dx.common.css";
import "devextreme/dist/css/dx.material.blue.dark.compact.css";

new Vue({
  router,
  store,
  render: h => h(App)
}).$mount("#app");
```

## App.tsx
```tsx
import { createComponent } from "@vue/composition-api";
import DxButton from "devextreme-vue/button";

export default createComponent({
  name: "App",
  setup() {
    return () => (
      <div id="app">
        <DxButton>Test</DxButton>
      </div>
    );
  }
});


```

### Environment Details
- devextreme: 19.2.5
- devextreme-vue: 19.2.5
- vue: ^2.6.10
- typescript: ~3.5.3
- @vue/cli-service: ^4.1.0

**Comment by coolhome** [comment]
I did some research into this... When I build this library myself but convert all these statements

```
import * as VueType from "ve";
const Vue = VueType.default || VuueType;
```

to be the following then the types definitions 

```
import Vue from "vue";
```

then the d.ts will work.

**Comment by JohnCampionJr** [comment]
I get this error as well when adding to a new standard project.  
I fixed by adding 
`import * as VueType from "vue";`
to the .d.ts type files that I was using.

**Comment by LexDX** [comment]
Thank you for the report. We are researching this issue in the context of the https://www.devexpress.com/Support/Center/Question/Details/T849089/devextreme-vue-the-cannot-find-namespace-vuetype-compilation-error-occurs-in-the ticket.
