### ISSUE TITLE
Vetur Support

### ISSUE THREAD

**Issue by coolhome** [DevExpress/devextreme-vue#347]
# Feature request

Add Vetur framework support for DevExterme. This will implement auto complete for DevExterme inside of Vetur (vscode plugin). Should be able to easily add a build step to generate the vetur `tags` and `attributes`.

## Useful References
[Vetur Framework Support](https://vuejs.github.io/vetur/framework.html)

Sample implementation from Buefy ([buefy-helper-json](https://github.com/buefy/buefy-helper-json)):
* [package.json](https://github.com/buefy/buefy-helper-json/blob/a335f16c1bbdb727417f1bb6b4a7199c0efc5d79/package.json#L31-L34)
* [tags.json](https://github.com/buefy/buefy-helper-json/blob/master/tags.json)
* [attributes.json](https://github.com/buefy/buefy-helper-json/blob/master/attributes.json)

**Comment by LexDX** [comment]
Hi,

Thank you for your suggestion. We will consider supporting the Vetur framework in the future. I can't give you any ETA though - please stay tuned to our Blog posts and 'What's New' articles.

**Comment by softboy99** [comment]
+1
