### ISSUE TITLE
Issue with dx-validator and child components when bundling is used as described in issue #84?

### ISSUE THREAD

**Issue by srinath999** [DevExpress/devextreme-vue#350]
I have used the  bundle with required components  using the example presented in issue #84 . I am facing an issue with the current demos posted in devextreme demos of dx-validation in vue.

I am running the bundle in production mode. I keep getting the error "Cannot find discover of undefined" when the field is updated and outfocused. when i look into the developer tools the code is $_templateManager.discover() is failing. I have registered my components in the order 
1. UI/Visible components.
2. DxValidator
3. different validation rules (DxRequiredRule) and others in the bundle.

components like dx-data-grid and dx-tree-view are not working with <template> tag is used as in demo https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/ColumnTemplate/Vue/Light/
where template is simply ignored. 
After not bring able find the issue we simply fell back cellTemplate method implementation.
Devextreme Version :19.2.4
Vue :  2+

**Comment by srinath999** [comment]
Here is a small demo which i could reproduce the issue
https://github.com/srinath999/devextreme-vue-issues 
I have also added a sample video of the issue.

**Comment by srinath999** [comment]
The solution from the issue  #195 seems to solve our problem but The component I am using is not a non-devextreme one. I would not expect that as a solution for the problem. Please take a look at the repo I have posted it also has a video explaining the issue. Any response would be appreciated!

**Comment by LexDX** [comment]
Hi @srinath999,

Please accept my apologies for the delayed response. We fixed this issue in the context of the following PR: https://github.com/DevExpress/devextreme-vue/pull/357. 

You can use the latest hotfix version to test this fix.

**Comment by srinath999** [comment]
Thank You very much for the fix.
