### ISSUE TITLE
DxDataGrid Gives different errors in different browsers when removing it from DOM Using v-if

### ISSUE THREAD

**Issue by srinath999** [DevExpress/devextreme-vue#359]
# Bug Report #

**Environment:**
We generate devextreme-vue bundle and use in application frameworks which support MVC.

**Code Sample:**
https://github.com/srinath999/devextreme-vue-issues/tree/grid-hide-issue

**Actions to Reproduce:**
Click on Hide/Show Button to see error in console.

**Expected behavior:**
Console runs smoothly without any issues.

**Screenshots** are available in the code sample.

Please leave a comment if the issue needs additional info.

**Comment by LexDX** [comment]
Hi @srinath999,

I reproduced the issue on my side and we will research why it occurs in the context of the following report in our Support Center: https://supportcenter.devexpress.com/ticket/details/t884904/devextreme-vue-the-typeerror-cannot-read-property-componentscountchanged-of-undefined

**Comment by srinath999** [comment]
I like that we have a work-around here but, validation is a critical part of any application. Is there a way to add a validator in Vue without using nested component i.e.., the dx-validator component.

**Comment by srinath999** [comment]
link #84
