### ISSUE TITLE
Devextreme templates are not working while using the bundling technique mentioned in issue #84

### ISSUE THREAD

**Issue by srinath999** [DevExpress/devextreme-vue#360]
# Bug Report
Devextreme templates in DxDatarid and DxList are not working when they are used as per repository examples or Devextreme Site Demos presented with 19.1.3 release. Sometimes they end up showing template name itself.
When we use functions to render templates They work fine. This is not ideal when you are writing lots of javascript already.

**Code Sample:**
https://github.com/srinath999/devextreme-vue-issues/tree/dx-template-demo 

**Package versions: ** 
They are mentioned in
https://github.com/srinath999/devextreme-vue-issues/blob/dx-template-demo/package.json

**Steps to reproduce:**
run `npm run build` and then `npm run serve` in the code sample

**Expected behavior:**
Templates should render seamlessly.

**Comment by srinath999** [comment]
Any Fix for this Issue will resolve items like dx-form, dx-item, dx-data-grid where they are extensively used and sometimes the only solution one can use.

**Comment by LexDX** [comment]
Hi @srinath999,

The issue occurs because scripts are rendered after the page HTML. So, to resolve the issue, please register them before the HTML content. For example, you can use the head section of the page or the beginning of the body section:
`
<body>
  <script src="https://unpkg.com/vue"></script>
  <script src="data.js"></script>
  <script src="js/app/bundle.js"></script>
  <div class="container">    
    //code
  </div>
  <script>
    new Vue({
      el: "#app",
      data: {
        dataSource: customers,
        items: [1, 2, 3, 4, 5, 6, 7],
        show: true
      }
    });
  </script>
</body>
`

**Comment by srinath999** [comment]
I cannot render templates that are offered by Devextreme like itemTemplate in DxList, cellTemplate in DxColumn using template (without Js functions) etc.., Could you please provide a sample for me on that?

**Comment by LexDX** [comment]
Hi @srinath999,

Yes, it looks like I overlooked some of your requirements. I apologize for that. I'll reopen the issue and research this behavior further. I'll let you know once I have any updates.

**Comment by LexDX** [comment]
As a temporary workaround, use the following syntax to create templates:

```
<dx-list :items="items" :itemTemplate="itemTemplate">
</dx-list>
```

```
new Vue({
  el: "#app",
  data: {
    items: [1, 2, 3, 4, 5, 6, 7],
    itemTemplate: function(data,index,element) {
      var elt=document.createElement("DIV");
      elt.innerText=data;
      element.append(elt);
    }
});
```

**Comment by LexDX** [comment]
Hi @srinath999,

Thank you for your patience. We researched the issue and found that we are unable to fix it in the current version of our controls. Such a change can affect existing customer scenarios and possibly break their projects. However, we will research the possibility of enhancing this behavior in future releases. 

As a workaround, I recommend using the syntax I shared earlier:
```
<dx-list :items="items" :itemTemplate="itemTemplate">
</dx-list>
```

```
new Vue({
  el: "#app",
  data: {
    items: [1, 2, 3, 4, 5, 6, 7],
    itemTemplate: function(data,index,element) {
      var elt=document.createElement("DIV");
      elt.innerText=data;
      element.append(elt);
    }
});
```

**Comment by srinath999** [comment]
link #84
