### ISSUE TITLE
Vite + Rollup build tool support for vue3

### ISSUE THREAD

**Issue by softboy99** [DevExpress/devextreme-vue#385]
Vite + Rollup build tool support for vue3

**Comment by LexDX** [comment]
Hi @softboy99 ,

In this scenario, I recommend you use the solution from this ticket: [https://supportcenter.devexpress.com/ticket/details/t956025/the-duplicate-export-hidecallback-error-occurs-on-an-attempt-to-build-an-application](https://supportcenter.devexpress.com/ticket/details/t956025/the-duplicate-export-hidecallback-error-occurs-on-an-attempt-to-build-an-application)

Also, we have plans to support ESM modules in the future, but I can't give you any ETA. Please check our blog posts and What's New articles for updates.

**Comment by softboy99** [comment]
please add vite support for devextreme cli
