### ISSUE TITLE
DxButton in cellTemplate doesn't have any options

### ISSUE THREAD

**Issue by altercode** [DevExpress/devextreme-vue#47]
### Issue Type

- [ x] bug report
- [ ] feature request

### Current Behavior
```
cellTemplate: function(cell, info) {
                  let test = new DxButton({
                        text: 'test123',
                        icon: 'arrowleft',
                        type: 'danger',
                        onClick: function (e) {
                            alert(options.text)
                        }
                  });
                  test.$mount();
                  cell.append(test.$el);
              }
```
I try to add dx-button into cellTemplate. This code generates empty button without any text, icon, background color and onClick event not working.

### Expected Behavior

this should display button with text and other options as well

**Comment by IlyaKhD** [comment]
Hi,
To pass props to a component during its creation you can use the [`propsData`](https://vuejs.org/v2/api/#propsData) option:

```js
cellTemplate: function(cell, info) {
                  let test = new DxButton({
                    propsData: {
                        text: 'test123',
                        icon: 'arrowleft',
                        type: 'danger',
                        onClick: function (e) {
                            alert(options.text)
                        }
                    }
                  });
                  test.$mount();
                  cell.append(test.$el);
              }
```

**Comment by altercode** [comment]
Hi,

Thank you. It works! How about the different approach that I covered here:

https://www.devexpress.com/Support/Center/Question/Details/T627810/set-celltemplate-in-dxdatagrid-vue-js-approach-18-1

to use named slot as a cellTemplate? Can you tell what is proper way of doing this?

**Comment by IlyaKhD** [comment]
The code example you've referred to looks to be OK, but there is a bug with the `cellTemplate` option itself.
I've filed an issue for it: #48, so you could track it to get notified once the bug is fixed.
