### ISSUE TITLE
dxDataGrid: selectedRowKeys not being updated

### ISSUE THREAD

**Issue by MAG-Christian-Birkl** [DevExpress/devextreme-vue#54]
### Issue Type

[x] 'bug report'

### Description

dxDataGrid selectedRowKeys is not being updated if the user changes the initial selection.

#### Expected Behavior

dxDataGrid two-way binds selectdRowKeys to the underlying array and updates changes.

### Steps to Reproduce

change grid-example.vue:

1) insert button to show current selection

```
  <dx-button text="Show selected" @click="showSelected" />`

  ...

  methods: {
	showSelected: function() {
		alert("selectedRowKeys: " + JSON.stringify(selectedKeys));
	}
  },
```
2) npm run serve
3) unselect or select some other rows beside the initial selection
4) click on "Show selected" - it only contains the initial selection

### Environment Details

- master as of 036025c9aa5129c34cc4f446bdbc89d8e6a34ede
- chrome 65.0.3325.181

**Comment by IlyaKhD** [comment]
Hi,

To make two-way binding work try this:
1) Use the `.sync` modifier for the `selectedRowKeys` option:
```jsx
<dx-data-grid 
  // ....
  :selectedRowKeys.sync="selectedRowKeys"
  // ....
>
```

2) Refer to the `selectedRowKeys` field of your instance data:
```js
alert("selectedRowKeys: " + JSON.stringify(this.selectedRowKeys))
````
instead of using to the `selectedKeys` constant.
```js
alert("selectedRowKeys: " + JSON.stringify(selectedKeys))
```

**Comment by MAG-Christian-Birkl** [comment]
ah thanks! - should have read the README ;-) 

works like a charm with your changes.
