### ISSUE TITLE
Modyfying a component parent state makes the component rerender

### ISSUE THREAD

**Issue by IlyaKhD** [DevExpress/devextreme-vue#55]
### Issue Type
bug report

#### Current Behavior
A component rerenders even if its parent changes don't affect the component itself

#### Expected Behavior
No re-render expected

### Steps to Reproduce
Use the examples app, grid-example.vue:
- add `a: 1,` to the components data
- add `{{a}} <button @click="a += 1">increase!</button>` to the `example-block` next to the `dx-data-grid`

### Environment Details
v18.1.1-alpha.2

**Comment by IlyaKhD** [comment]
This also affects two-way binding, see #54.

**Comment by denour** [comment]
Hello, how can I make a custom row with data grid I'm using a column object where I have this line:
`        cellTemplate: 'cellTemplate',`

and this is my template where I want to change it but it doesnt work

```
 <div slot="cellTemplate" slot-scope="cell">
                                <div style="color:blue">{{cell.text}}</div>
                            </div>
```

can you help me, please?

**Comment by IlyaKhD** [comment]
Hi, @denour

Could you file [a new issue](https://github.com/DevExpress/devextreme-vue/issues/new) for your question?

**Comment by denour** [comment]
Yes, Thank you.

**Comment by lukyanovas** [comment]
Objects are hardcoded in the template of the grid-example.vue. This is not a good way to set a complex prop. Re-rendering happens because all component props have watchers and after rendering of grid-example.vue these hardcoded objects does not equal, so "new" props pass to a widget. 
I'll fix our examples to avoid this issue.
