### ISSUE TITLE
How can I make a custom row with data grid?

### ISSUE THREAD

**Issue by denour** [DevExpress/devextreme-vue#59]
### Issue Type
Question

### Description
how can I make a custom row with data grid?

#### Steps to Reproduce
In my columns vector I have an object like this:
`{
        dataField: 'Status',
        cellTemplate: 'cellTemplate',
        caption: 'Status'
 }`

in the HTML code I have this:

``` 
<dx-data-grid
     :dataSource="contribuyentes"
     :columns="columns"
     :paging="paging"
     :headerFilter="{ visible: true }">
     <div slot="cellTemplate" slot-scope="cell">
         <div style="color:blue">{{cell.text}}</div>
      </div>
</dx-data-grid>
```

**Comment by IlyaKhD** [comment]
Hi, @denour!

Could you clarify, what exactly works wrong (current behavior vs expected behavior)?

In my environment, the code sample you provided renders the Status column text in blue.

**Comment by denour** [comment]
I want to render the status of a user with an icon like [this](https://imgur.com/Aju3VTQ).
but I dont know how to customize the grid like that.

**Comment by IlyaKhD** [comment]
You can use `cellTemplate` to customize a column cells markup (e.g. adding an icon).

This repository is for the Vue integration, for questions regarding DevExtreme libraries and widgets' APIs, use the [DevExpress Support Center](https://www.devexpress.com/Support/Center).
