### ISSUE TITLE
i want to data grid inner object(dxTextBox) instance.

### ISSUE THREAD

**Issue by yosiah** [DevExpress/devextreme-vue#65]
### Issue Type

feature request

### Description

```html
<dx-data-grid 
        ref="buildingGrid"
        :onEditorPrepared="onEditorPrepared"
        :data-source="buildingList" 
>
</dx-data-grid>
```

```js
export default {
  data () {
    return {
      onEditorPrepared: function(e) {
        if (e.dataField === "building" ) {
          //console.log(e);
          
          e.editorElement.dxTextBox("instance").option("mask", "L");
          //e.editorElement.dxTextBox not function

          e.editorElement.instance.option("mask", "L");
          //e.editorElement.instance not instance
        }
      }
    }
  }
}
```
i want to data grid inner object(dxTextBox) instance.

**Comment by IlyaKhD** [comment]
Hi,

Try using [the `getInstance` method](https://js.devexpress.com/Documentation/18_1/ApiReference/UI_Widgets/dxTextBox/Methods/#getInstanceelement) (the `editorElement` field holds reference to an HTML Element).

For further questions on DevExtreme widgets' APIs, please use [the DevExpress Support Center](https://www.devexpress.com/Support/Center).

**Comment by yosiah** [comment]
Hi.
Thank you for your interest.

Try using [the getInstance method](https://js.devexpress.com/Documentation/18_1/ApiReference/UI_Widgets/dxTextBox/Methods/#getInstanceelement)


`onEditorPrepared: function(e) {
        if (e.dataField === "building" ) {
          //console.log(e);
          
          //i want to runtime text box option change inner data grid.

         let edit = new DxTextBox(e.editorElement) 
         // this is new instance

         DxTextBox.getInstance(e.editorElement)
         //18.1 devextreme-vue DxTextBox component not has getInstance function

        }
      }`
