### ISSUE TITLE
How to bind selected row in dx-drop-down-box with nested dx-data-grid to v-model.

### ISSUE THREAD

**Issue by tjq** [DevExpress/devextreme-vue#69]
### Issue Type
Question

### Description
I am looking for a way to bind the selection of the nested grid (within a dropdown box) to a v-model.

#### Steps to Reproduce
In my Vue component, I have an array of objects `items`, each with several props. I've shortened it to display only the `itemName` prop, while the value I'd like to pass to the v-model is the `id` prop.

```html
 <dx-drop-down-box
   :data-source="items"
   displayExpr="itemName"
   valueExpr="id"
   v-model="itemToAdd">
    <div slot="content" slot-scope="data">
        <dx-data-grid
           :columns="[{ dataField: 'itemName' }]"
           :data-source="items" 
           :allow-column-reordering="true"
           :onSelectionChange="(items) => { console.log(items) }" 
           :paging="{ pageSize: 5 }"
           :filter-row="{ visible: true }"
           :selection="{ mode: 'multiple' }"
         >
         </dx-data-grid>
     </div>
</dx-drop-down-box>
```

#### Current Behavior
The grid renders as expected but the model (`itemToAdd`) is not updated when a row is selected. I supposed I could use the `:onSelectionChange` method and assign the `itemToAdd` in a vue method, but I imagine there is a simpler way to do this.

#### Expected Behavior
I would like it to behave like the second dropdown in the following CodePen: https://js.devexpress.com/Demos/WidgetsGallery/Demo/DropDownBox/SingleSelection/jQuery/Light/.

### Environment Details
Using latest devextreme-vue installed using npm.

**Comment by IlyaKhD** [comment]
Hi,

You can use [the selectedRowKeys option](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/#selectedRowKeys):
1. Set the DataGrid `keyExpr` value to `"id"` (as you're using this field as the DropDownBox `valueExpr`)
1. Bind the `itemToAdd` prop to the DataGrid `selectedRowKeys` option (don't forget to use the `.sync` modifier)

```html
<dx-drop-down-box
   :data-source="items"
   displayExpr="itemName"
   valueExpr="id"
   v-model="itemToAdd">
    <div slot="content" slot-scope="data">
        <dx-data-grid
           :columns="[{ dataField: 'itemName' }]"
           keyExpr="id"
           :selectedRowKeys.sync="itemToAdd"
           :data-source="items"
           :allow-column-reordering="true"
           :onSelectionChange="(items) => { console.log(items) }" 
           :paging="{ pageSize: 5 }"
           :filter-row="{ visible: true }"
           :selection="{ mode: 'multiple' }"
         >
         </dx-data-grid>
     </div>
</dx-drop-down-box>
```

**Note**: the `itemToAdd` prop actually stores an array of selected items keys, thus multi-selection is available.

**Comment by KazievKazi** [comment]
```
<dx-drop-down-box
                :data-source="posts4"
                displayExpr="login"
                valueExpr="login"
                :showClearButton="true"
                v-model="tbmessagesa2"
                >
                    <div slot="content">
                        <dx-data-grid
                        :columns="[{ dataField: 'login', caption: 'Телефон' },
                        { dataField: 'name', caption: 'Имя' },
                        { dataField: 'gender', caption: 'Пол' },
                        { dataField: 'town', caption: 'Город' }]"
                        keyExpr="login"
                        :onSelectionChange="(posts4) => { console.log(posts4) }"
                        :selectedRowKeys.sync="tbmessagesa2"
                        :data-source="posts4"
                        :height="340"
                        :allow-column-reordering="true"
                        :headerFilter="{ visible: true }"
                        :scrolling="{ mode: 'infinite' }"
                        :selection="{ mode: 'multiple' }"
                        >
                        </dx-data-grid>
                    </div>
                </dx-drop-down-box>
```
что не правильно в моем коде?
считывает только одну строчку! в самом начале, событие вроде есть, но видит только первую выбранную строчку, последующие выбранные строчки (то есть 2ая, 3яя, 4ая и тд,) не отображаются.
