### ISSUE TITLE
the masterDetail of data-grid ,how to use a template showing the datailData

### ISSUE THREAD

**Issue by xuejulong** [DevExpress/devextreme-vue#76]
Now, I want to add masterDetail in the DxDataGrid control. However, I cannot create a template to display complex data such as picture,chart and tables. How do I do this in vue?

**Comment by lukyanovas** [comment]
Hi!
To create templates in DevExtreme Vue Components, use [the slot functionality](https://github.com/DevExpress/devextreme-vue#custom-templates).
See this [example](https://codesandbox.io/s/046mynrx0n).

**Comment by ru-pacman** [comment]
Hello :)
Your example doesn't work. Please add a current example.
I use the latest (18.1.6-alpha.9) version and the contents of the slot are not rendered.

Example:
```html
<dx-data-grid keyExpr="Id" v-bind="{
        dataSource: dataSource,
        masterDetail: {enabled: true, template: 'qwe'}
    }">
        <dx-column dataField="Title"/>
        <dx-column dataField="Type"/>
        <dx-column dataField="ClientIp"/>
        <dx-column dataField="Size"/>
        <div slot="qwe" slot-scope="value">{{'test value: ' + value}}</div>
    </dx-data-grid>
```

**Comment by ru-pacman** [comment]
Ok. 
I did everything as indicated in your example (in the corrected object in which there should be data). But I still can not display the result, just get an error:
```
Uncaught TypeError: Cannot read property 'add' of undefined
    at Object.render (eval at globalEval (core?url=./bundles/js/shared.js:1), <anonymous>:1795:39)
    at inheritor.renderDelayedTemplates (eval at globalEval (core?url=./bundles/js/shared.js:1), <anonymous>:43680:41)
    at inheritor.renderDelayedTemplates (eval at globalEval (core?url=./bundles/js/shared.js:1), <anonymous>:51555:35)
    at inheritor.eval [as renderDelayedTemplates] (eval at globalEval (core?url=./bundles/js/shared.js:1), <anonymous>:5620:27)
    at inheritor._renderCore (eval at globalEval (core?url=./bundles/js/shared.js:1), <anonymous>:43762:18)
    at inheritor.eval [as _renderCore] (eval at globalEval (core?url=./bundles/js/shared.js:1), <anonymous>:5620:27)
    at inheritor._renderCore (eval at globalEval (core?url=./bundles/js/shared.js:1), <anonymous>:52897:26)
    at inheritor.eval [as _renderCore] (eval at globalEval (core?url=./bundles/js/shared.js:1), <anonymous>:5620:27)
    at inheritor._renderCore (eval at globalEval (core?url=./bundles/js/shared.js:1), <anonymous>:54256:26)
    at inheritor.eval [as _renderCore] (eval at globalEval (core?url=./bundles/js/shared.js:1), <anonymous>:5620:27)
```

**Comment by evgencode** [comment]
The same error for me
`VM21271:13204 Uncaught TypeError: Cannot read property 'add' of undefined
    at Object.render (eval at globalEval (core?url=./bundles/js/shared.js:1), <anonymous>:13204:39)
    at Object.render (eval at globalEval (core?url=./bundles/js/shared.js:1), <anonymous>:102317:38)`

**Comment by evgencode** [comment]
The same problem:
![image](https://user-images.githubusercontent.com/2129431/50163496-9dd70880-02f1-11e9-9bb9-982023d83895.png)
![image](https://user-images.githubusercontent.com/2129431/50163538-b2b39c00-02f1-11e9-9453-9b3e66c7b506.png)

**Comment by IlyaKhD** [comment]
@evgencode, could you file a new issue and provide a live example, demonstrating the problem? You can modify [this one](https://codesandbox.io/s/github/lukyanovas/devextreme-vue-example).

**Comment by evgencode** [comment]
> @evgencode, could you file a new issue and provide a live example, demonstrating the problem? You can modify [this one](https://codesandbox.io/s/github/lukyanovas/devextreme-vue-example).

I just use build Vue + compilator.
When I use import Vue from 'vue' - everything is good, BUT, when I use import Vue from 'vue/dist/vue'; (vue Runtime + Compilator) - I see a lot of bugs.
An also I found new bug. 
![image](https://user-images.githubusercontent.com/2129431/50332765-38169680-0514-11e9-8a0c-c86de8efe13a.png)
When I try to change the dataSource after mounting

**Comment by evgencode** [comment]
> @evgencode, could you file a new issue and provide a live example, demonstrating the problem? You can modify [this one](https://codesandbox.io/s/github/lukyanovas/devextreme-vue-example).

Please try this code:

**main.js:**
`import Vue from 'vue/dist/vue';
import App from './App.vue';

new Vue({
  render: function(h) {
    return h(App);
  }
}).$mount('#app');`

**App.vue:**

`<template>
  <Example v-bind:rows="protos"/>
</template>

<script>
import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.material.blue.light.css';
import Example from './components/Example';
import { sales } from './components/data';

export default {
  name: 'App',
  data() {
    return {
      protos: sales
    };
  },
  components: {
    Example
  },
  mounted() {
    setTimeout(() => {
      this.protos = [
        {
          orderId: 125,
          region: 'NEW 1',
          country: 'Narniya',
          city: 'Gopa',
          amount: 1740,
          date: '2013/01/06'
        }
      ];
    }, 2000);
  }
};
</script>`

### ./components/Example:

`<template>
  <dx-data-grid keyExpr="orderId" v-bind="{
      dataSource: rows,
      masterDetail: {enabled: true, template: 'qwe'}
  }">
    <div slot="qwe" slot-scope="value">{{'test value: ' + value.data.country}}</div>
  </dx-data-grid>
</template>

<script>
import { DxDataGrid } from 'devextreme-vue/ui/data-grid';

export default {
  components: {
    DxDataGrid
  },
  props: ['rows']
};
</script>`

### ./components/data:

`export const sales = [
{
    orderId: 10248,
    region: 'North America',
    country: 'United States',
    city: 'New York',
    amount: 1740,
    date: '2013/01/06'
  },
  {
    orderId: 10249,
    region: 'North America',
    country: 'United States',
    city: 'Los Angeles',
    amount: 850,
    date: '2013/01/13'
  }
]`

**Comment by evgencode** [comment]
> @evgencode, could you file a new issue and provide a live example, demonstrating the problem? You can modify [this one](https://codesandbox.io/s/github/lukyanovas/devextreme-vue-example).

The issue: https://github.com/DevExpress/devextreme-vue/issues/221
