### ISSUE TITLE
TextBox - The valueChanged event does not fire inside DOM templates

### ISSUE THREAD

**Issue by NickMitrokhin** [DevExpress/devextreme-vue#77]
Can be reproduced [here](https://codesandbox.io/s/y314q0k4yx). 

For those who encounter the same issue, use the following workaround:

`<dx-text-box :value="myValue" :on-value-changed="onValueChanged">
</dx-text-box>`

**Comment by IlyaKhD** [comment]
Inside DOM templates events names are supposed to be [in the kebab-case](https://vuejs.org/v2/guide/components-custom-events.html#Event-Names), which is currently not supported.

Gonna fix it.
