### ISSUE TITLE
Unable to use the DevExtreme editors validation

### ISSUE THREAD

**Issue by NickMitrokhin** [DevExpress/devextreme-vue#78]
The "Adapter for a DevExpressValidator component cannot be configured" error is thrown when Validator is assigned to an editor

Can be reproduced [here](https://codesandbox.io/s/18nr3311z3).

**Comment by robbash** [comment]
I checked with latest changes and cannot confirm this issue fixed.

**Comment by IlyaKhD** [comment]
@robbash, the fix is going to be delivered in the next alpha, see the [18.1.4-alpha.5](https://github.com/DevExpress/devextreme-vue/milestone/3) milestone.

**Comment by robbash** [comment]
Then I got confused by closing this issue. So there will be more changes to actually fix this?

**Comment by IlyaKhD** [comment]
No more changes expected for this.
The changes made in the #92 are enough to fix the issue.

Did you mean that you've checked out the master branch and tried the examples?

**Comment by lukyanovas** [comment]
There is a typo in the first sample. 
Should be
```js
      rules: [
        {
          type: "required",
          message: "this is required"
        }
      ]
```
Instead of
```js
      rules: [
        {
          required: true,
          message: "this is required"
        }
      ]
```
Updated [sample](https://codesandbox.io/s/mo598mz2lj) (Now works as expected with 18.1.4-alpha.5)

**Comment by robbash** [comment]
Today the `yarn` command came up with a dependency mismatch for the `devextreme` package. After upgrading to `devextreme@18.1.4-pre-18155` it works as expected!

Thanks a lot!!
