### ISSUE TITLE
how to use router-link Component from Vue router on devextreme widgets slot 

### ISSUE THREAD

**Issue by zisiszaverdas** [DevExpress/devextreme-vue#79]
### Issue Type
question

### Description
i tried to create a navigation list based on vue-router but when i used  router-link component on the slot of dxlist it throws an error. I am not sure if my integration is correct and indeed there is a compatibility issue.

#### Steps to Reproduce
```
<dx-list :data-source="dataSource" :visible="visible">
    <div slot="item" slot-scope="data">
        <router-link to="/">test</router-link>
    </div>
</dx-list>
```
#### Demo
[https://codesandbox.io/s/6woj973v3k](https://codesandbox.io/s/6woj973v3k)

**Comment by lukyanovas** [comment]
Hi, 
It looks like a bug in our components.
