### ISSUE TITLE
How to use validation with TextBox?

### ISSUE THREAD

**Issue by rodrigorodriguescosta** [DevExpress/devextreme-vue#83]
### Description

How to use validation with TextBox?
How to pass validations options to component?

Ex: [https://js.devexpress.com/Demos/WidgetsGallery/Demo/Validation/Overview/jQuery/Light/](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Validation/Overview/jQuery/Light/)

**Comment by IlyaKhD** [comment]
Hi

Currently, this is not supported, you can track this issue: #78.
