### ISSUE TITLE
can devextreme be used without a module loader?

### ISSUE THREAD

**Issue by jcomet** [DevExpress/devextreme-vue#84]
### Issue Type

Question
### Description
We have many simple scenarios where we simply include vue without a module loader.  Can the devextreme wrappers be used that way, by using link and script tags to bring in the assets?

**Comment by kingcomxu** [comment]
+1

**Comment by IlyaKhD** [comment]
Hi,

Though we don't provide a kind of "all-components-bundle" out of the box you can create your own according to your needs (e.g. include only components required).

I've created a simple bundler based on our [WebPack Vue example](https://github.com/DevExpress/devextreme-examples/tree/18_1/webpack-vue).

1) Add the **devextreme-vue.js** file and register all the components you need. Choosing components names (like `'dx-popup'` below) is up to you.
```js
import { DxButton } from 'devextreme-vue/ui/button';
import { DxPopup } from 'devextreme-vue/ui/popup';

Vue.component('dx-button', DxButton);
Vue.component('dx-popup', DxPopup);
```
You can find more details on Vue global component registration [here](https://vuejs.org/v2/guide/components-registration.html#Global-Registration).

2) Update the **webpack.config.js** file:
```js
...
  entry: './devextreme-vue.js',
  output: {
    filename: './public/js/app/devextreme-vue.js',
  },
...
```
3) After running `npm run build` in the console you can use the generated file (**./public/js/app/devextreme-vue.js**) to bring the DevExtreme Components whithout module loaders. 

4) Include the **devextreme-vue.js** file and CSS-theme files to your page:


```html
<head>
  ...
  <link rel='stylesheet' type='text/css' href='https://cdn3.devexpress.com/jslib/18.1.3/css/dx.common.css' />
  <link rel='stylesheet' type='text/css' href='https://cdn3.devexpress.com/jslib/18.1.3/css/dx.material.blue.light.css' />
</head>

<body>
  <div id='app'></div>

  <script src='https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.js'></script>
  <script src='../dist/public/js/app/devextreme-vue.js'></script>
  <script>
    new Vue({
      el: '#app',
      template: '<dx-button text="click me" icon="plus" />'
    });
  </script>
</body>
```


5) You can customize the CSS-theme as well with the help of the [Theme Builder](https://js.devexpress.com/Documentation/Guide/Themes/Theme_Builder/).

I've also attached an archive with the example: [example.zip](https://github.com/DevExpress/devextreme-vue/files/2048422/example.zip).

**Comment by jcomet** [comment]
Thanks IlyaKhD.   That helps a lot, but I found an issue.   I get many warnings from vue with the textbox and others.    I took your example, added dxTextBox.

`import { DxButton } from 'devextreme-vue/ui/button';
import { DxPopup } from 'devextreme-vue/ui/popup';
import { DxTextBox } from 'devextreme-vue/ui/text-box';

Vue.component('dx-button', DxButton);
Vue.component('dx-popup', DxPopup);
Vue.component('dx-text-box', DxTextBox);`

Then added it to index.html:
`  
<script>

    new Vue({
      el: '#app',
      template: `
<div>
<dx-button text="click me" icon="plus" />
<dx-text-box v-model="first_name"></dx-text-box>	  
</div>`,
	  data: {
		first_name: 'Joe'
	  }
    });
  </script>`

after loading index.html, i saw that the model binding worked, but if I enter anything in the textbox then tab off, I get errors: 

vue.esm.js:592 [Vue warn]: $attrs is readonly.
[Vue warn]: $listeners is readonly.

![2018-06-02_12-29-47](https://user-images.githubusercontent.com/109494/40878565-eebb377c-6660-11e8-99e7-8bd95a37cca7.png)

I have tried this in different configurations in different projects with the same results.

I have attached an updated example to show the problem.

[example_with_textbox.zip](https://github.com/DevExpress/devextreme-vue/files/2065160/example_with_textbox.zip)

**Comment by Code-Codex** [comment]
Is the devexpress library bundled up there in the js created. I have both jQuery and vue components on the same page. And have the devextreme js file included in the page along with the js created from the method described above.. Will this be a problem?

**Comment by Alain-WS** [comment]
I did this with the data grid and other necessary components and the generated file is 5.34Mb...

This is completely unusable in a real world scenario.

**Comment by srinath999** [comment]
> I did this with the data grid and other necessary components and the generated file is 5.34Mb...
> 
> This is completely unusable in a real-world scenario.

The production build would be of  size < 2MB. Please Change the **mode** in Wepack.config.js to "production" to check this . Please take a good risk analysis before consuming the library this way. It is not completely supported at the moment. I suggest you take a look at the linked issues to this issue.

**Comment by uropb3** [comment]
How can I use this instruction with Vue 3? In the Vue 3 global component registration is organized differently (if I understood correctly what the problem is). 
Can you give me an instruction for this example: https://github.com/DevExpress/devextreme-examples/tree/21_1/webpack-vue?
