### ISSUE TITLE
DxSelectBox not set event onOpened

### ISSUE THREAD

**Issue by yosiah** [DevExpress/devextreme-vue#86]
### Issue Type

bug report

### Description
DxSelectBox not set event onOpened

#### Current Behavior
[HTML]
`                  <dx-form ref="searchForm"
                    :formData="searchPanel.data"
                           :items="searchPanel.items"
                           :showColonAfterLabel="false"
                           :alignItemLabel="true"
                           labelLocation="left"
                           :minColWidth="100"
                           :colCount="5"
                           :onOpened="searchPanel.onOpened"
                           width="auto"
                  >`
[js]
`      searchPanel: {
        data: {
          CORP_ID: ""
        },
        items: [{
          label: { text: 'CORP' },
          dataField: 'CORP_ID',
          editorType: 'dxSelectBox',
          editorOptions: {
            value: "",
            items: lcorpList,
            displayExpr: 'NAME',
            valueExpr: 'CODE',
            width: "200"
          },
        onOpened: (e)=>{
          console.log("searchPanel-onOpened()")
          //can not set onOpened event
        }`

#### Demo

like as test
https://codepen.io/anon/pen/awgqVa

### Environment Details

18.1.2-alpha.3

**Comment by IlyaKhD** [comment]
Could you clarify the steps to reproduce the issue? I've added an `alert` command to the example you provided and it is fired as expected: [codepen](https://codepen.io/ilyakhd/pen/BVNXJb?editors=0010).

**Comment by lukyanovas** [comment]
Hi!
I see that everything works as expected in this DevExtreme Vue [example](https://codesandbox.io/s/6zzn90xxxr).
If you need a further support, feel free to file a ticket in the [DevExpress Support Center](https://www.devexpress.com/Support/Center).
