### ISSUE TITLE
An error occurs when using the DataGrid Filter feature.

### ISSUE THREAD

**Issue by hyun-keun-cho** [DevExpress/devextreme-vue#87]
### Issue Type

bug report

### Description
![image](https://user-images.githubusercontent.com/38148802/40633124-91c6e10a-6328-11e8-8768-2f73586181b9.png)

If you enter filterrow and click the OK button, the following error occurs.

Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

#### Steps to Reproduce

```
...
<dx-data-grid
            :pager="dataGridOption.pager"
           :paging="dataGridOption.paging"
           :dataSource="dataGridOption.dataSource"
           :selection="dataGridOption.selection"
           :columns="dataGridOption.columns"
           :showBorders="dataGridOption.showBorders"
           :filterPanel="dataGridOption.filterPanel"
           :filterRow="dataGridOption.filterRow"
           :height="gridHeight"
>
</dx-data-grid>
...

export default {
   ...
  dataGridOption: {
    ...
    filterRow = {
      applyFilter: 'auto',
      applyFilterText: 'Apply filter',
      betweenEndText:    'End',
      betweenStartText: 'Start',
      operationDescriptions: {},
      resetOperationText: 'Reset',
      showAllText: '',
      showOperationChooser: true,
      visible: true
    }
   ...
  }
}
```

**Comment by IlyaKhD** [comment]
Hi,

I'm unable to reproduce the issue, could you provide an example project?
You could use our [live example](https://codesandbox.io/s/kk5rrm1o2v) for this.

**Comment by hyun-keun-cho** [comment]
I did not give proper explanation. Sorry.

This problem has been solved by itself.

The problem was the rownumber column in the columns option.
```
{
  caption: 'No.',
  width: 50,
  cellTemplate: function (cellElement, cellInfo) {
    const pageSize = cellInfo.component.pageSize()
    const pageIndex = cellInfo.component.pageIndex()
    cellElement.append((pageSize * pageIndex) + cellInfo.row.rowIndex + 1)
  },
  allowEditing: false
}
```

I did not put the 'dataField' option here, and this caused an error.

The problem has been solved, but the rownumber column does not need to appear

Could you solve this?

**Comment by IlyaKhD** [comment]
Try setting the `allowFiltering` option to `false` (for the rownumber column).

**Comment by hyun-keun-cho** [comment]
It work! thanks!
