### ISSUE TITLE
Getting warnings after creating a custom bundle as described in issue 84.

### ISSUE THREAD

**Issue by jcomet** [DevExpress/devextreme-vue#90]
### Description
After following the solution from issue #84 I get **`[Vue warn]: $attrs is readonly`** errors after binding a dx-text-box. 

#### Steps to Reproduce

Starting with the example solution, i added the dxtextbox to devextreme-vue.js:

```javascript
import { DxButton } from 'devextreme-vue/ui/button';
import { DxPopup } from 'devextreme-vue/ui/popup';
import { DxTextBox } from 'devextreme-vue/ui/text-box';

Vue.component('dx-button', DxButton);
Vue.component('dx-popup', DxPopup);
Vue.component('dx-text-box', DxTextBox);`
```
Then added it to index.html:
```javascript

  <script>

    new Vue({
      el: '#app',
      template: `
<div>
<dx-button text="click me" icon="plus" />
<dx-text-box v-model="first_name"></dx-text-box>	  
</div>`,
	  data: {
		first_name: 'Joe'
	  }
    });
  </script>
```
Then:

1. open index.html in a web browser
2. F12 and show the javascript console
3. enter something in the textbox and tab off

#### Current Behavior
Get warnings in the console:
[Vue warn]: $attrs is readonly.
[Vue warn]: $listeners is readonly.
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "value"

![2018-06-02_12-29-47](https://user-images.githubusercontent.com/109494/40880095-c1900eea-6678-11e8-922d-f6c5c8f04b07.png)

#### Expected Behavior
no warnings or errors
#### Demo

updated example from #84 

[example_with_textbox.zip](https://github.com/DevExpress/devextreme-vue/files/2065292/example_with_textbox.zip)

**Comment by lukyanovas** [comment]
Hi!
The Vue library is included twice in your application. This is the reason of these warnings.
One is included in `index.html`:
```html
  <script src='https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.js'></script>
```
And the another one is included in your custom devextreme bundle (Vue is a DevExtreme Vue Components peer dependency)


To resolve this issue you should mark vue dependency as [external](https://webpack.js.org/configuration/externals/) in `webpack.config`:
```js
  externals: {
    vue: "Vue"
  },
```


Another way is to add Vue to your `devexteme-vue.js` bundle and use it in you application . Remove Vue script tag from you `index.html` and add these lines to `devexteme-vue.js`:
```js
import Vue from 'vue';
window.Vue = Vue;
```


I've updated the #84 to resolve the issue.
