### ISSUE TITLE
dxdatagrid exportToExcel -> No data is displayed in the Excel file.

### ISSUE THREAD

**Issue by yosiah** [DevExpress/devextreme-vue#93]
### Issue Type
bug report

### Description
dxdatagrid exportToExcel
(function and grid inner event)

The Excel file is downloaded.
However, if you open the downloaded Excel file,
It is downloaded as an empty Excel file with no data.

#### Demo
like as
https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/ExportToExcel/jQuery/Light/

### Environment Details

18.1.2-alpha.3

**Comment by IlyaKhD** [comment]
Hi,

Checked the link above, works OK for me. Could you provide an example project?
You could use our [live example](https://codesandbox.io/s/kk5rrm1o2v) for this.

**Comment by yosiah** [comment]
https://codesandbox.io/s/4oqzmw0r4

good working - dxdatagrid exportToExcel

Our package set ... problem ??

  "dependencies": {
    "axios": "^0.18.0",
    "babel-polyfill": "^6.26.0",
    "body-parser": "^1.18.3",
    "devextreme": "^18.1.3",
    "devextreme-vue": "^18.1.2-alpha.3",
    "es6-promise": "^4.2.4",
    "express": "^4.16.3",
    "express-session": "^1.15.6",
    "font-awesome": "^4.7.0",
    "loadash": "^1.0.0",
    "mdi": "^2.2.43",
    "nuxt": "^1.4.0",
    "postcss": "^6.0.22",
    "postcss-loader": "^2.1.5",
    "resize-observer-polyfill": "^1.5.0",
    "vue-cookie": "^1.1.4",
    "vue-i18n": "^7.7.0",
    "vuetify": "^1.0.17",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "babel-eslint": "^7.2.3",
    "babel-plugin-transform-imports": "^1.5.0",
    "callback-loader": "^0.2.4",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2",
    "eslint": "^4.19.1",
    "eslint-config-standard": "^11.0.0",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-html": "^4.0.3",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-node": "^6.0.1",
    "eslint-plugin-promise": "^3.8.0",
    "eslint-plugin-standard": "^3.1.0",
    "eslint-plugin-underscore-lodash-compatibility": "^0.1.0"
  },
  "resolutions": {
    "nuxt/vue": "^2.5.2"
  }

**Comment by yosiah** [comment]
https://codesandbox.io/s/7wn7nvppmx

multi row header 
dxdatagrid exportToExcel good working.

but, our code has problem.

https://imgur.com/gooHcbx

**Comment by lukyanovas** [comment]
Hi!
It seems that the problem is not the Vue integration issue.
If you need further assistance, I suggest you open a ticket in our [Support Center](www.devexpress.com/ask)

**Comment by yosiah** [comment]
our grid setting and data - sample code 
sample code has problem too.

https://codesandbox.io/s/7wn7nvppmx
